"""Designed demonstration scenarios (not random noise).

The cast is built so the matching system has something meaningful to rank:

* Job "Senior Backend Engineer" (Northwind Labs) is the showcase. Alex is a strong match; Elena is a partial match (Django
  instead of FastAPI, thinner infra); Gabe is a Java/Spring engineer (semantically adjacent, wrong stack); Farah is junior with
  MySQL (related-skill credit, below the experience bar); Mateo is a career changer; Bianca (frontend) and Julia (ICU nurse)
  are weak/irrelevant matches.
* Each other job has one clearly-best candidate, one decent alternative, and unrelated candidates.
* Non-tech roles (nursing, marketing, finance) prove the matcher is not "developer-only".

Years are relative to "today" so the data never looks stale.
"""

from __future__ import annotations

from typing import Any

PASSWORD = "DemoPass123!"  # published demo password; the seed refuses to run in production

COMPANIES: list[dict[str, Any]] = [
    {
        "key": "northwind",
        "name": "Northwind Labs",
        "industry": "Software & AI",
        "location": "Berlin, Germany",
        "size": "51-200",
        "website": "https://northwind.example.com",
        "description": "Northwind Labs builds developer tooling and applied-AI products used by engineering teams across Europe.",
        "recruiter": {
            "email": "recruiter@demo.example",
            "first": "Riley",
            "last": "Recruiter",
            "title": "Lead Technical Recruiter",
        },
        "staff": [
            {
                "email": "hiring.manager@demo.example",
                "first": "Hannah",
                "last": "Manager",
                "role": "HIRING_MANAGER",
                "title": "Engineering Manager",
            },
            {
                "email": "recruiter.two@demo.example",
                "first": "Ravi",
                "last": "Patel",
                "role": "RECRUITER",
                "title": "Recruiter",
            },
        ],
    },
    {
        "key": "helio",
        "name": "Helio Health",
        "industry": "Healthcare",
        "location": "Boston, USA",
        "size": "201-1000",
        "website": "https://helio.example.com",
        "description": "Helio Health runs a network of hospitals and outpatient clinics focused on critical and preventive care.",
        "recruiter": {
            "email": "recruiter.helio@demo.example",
            "first": "Helen",
            "last": "Okafor",
            "title": "Talent Partner",
        },
        "staff": [],
    },
    {
        "key": "brightwave",
        "name": "Brightwave Marketing",
        "industry": "Marketing & Advertising",
        "location": "London, United Kingdom",
        "size": "11-50",
        "website": "https://brightwave.example.com",
        "description": "Brightwave is a growth marketing agency helping B2B software companies earn attention and pipeline.",
        "recruiter": {
            "email": "recruiter.brightwave@demo.example",
            "first": "Bea",
            "last": "Whitfield",
            "title": "People Lead",
        },
        "staff": [],
    },
    {
        "key": "orbit",
        "name": "Orbit Finance",
        "industry": "Financial Technology",
        "location": "Amsterdam, Netherlands",
        "size": "201-1000",
        "website": "https://orbit.example.com",
        "description": "Orbit Finance provides payments infrastructure and analytics for European fintechs and banks.",
        "recruiter": {
            "email": "recruiter.orbit@demo.example",
            "first": "Omar",
            "last": "Haddad",
            "title": "Senior Recruiter",
        },
        "staff": [],
    },
]

ADMIN = {"email": "admin@demo.example", "first": "Ada", "last": "Admin"}

# status: DRAFT | PUBLISHED | PAUSED | CLOSED | ARCHIVED ; days_ago = when it was published
JOBS: list[dict[str, Any]] = [
    {
        "key": "backend",
        "company": "northwind",
        "title": "Senior Backend Engineer",
        "department": "Platform",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (90000, 120000),
        "min_exp": 4,
        "max_exp": None,
        "level": "SENIOR",
        "education": "BACHELOR",
        "status": "PUBLISHED",
        "days_ago": 21,
        "deadline_days": 40,
        "hiring_manager": "hiring.manager@demo.example",
        "description": "Join the platform team that builds the APIs behind Northwind's developer products. You will design, build and operate "
        "high-throughput Python services backed by PostgreSQL and Redis, own reliability end to end and mentor engineers.",
        "responsibilities": "Design and ship REST APIs with FastAPI. Model data and tune PostgreSQL queries. Build background workers and caching with Redis. "
        "Containerise services with Docker and improve CI/CD. Review code and mentor teammates.",
        "qualifications": "4+ years building production backend services. Strong Python. Solid SQL and database design. Comfortable owning services in production.",
        "benefits": "Hybrid work, learning budget, 30 days vacation, equity.",
        "skills": [
            ("Python", "REQUIRED"),
            ("FastAPI", "REQUIRED"),
            ("PostgreSQL", "REQUIRED"),
            ("Redis", "REQUIRED"),
            ("Docker", "REQUIRED"),
            ("Kubernetes", "PREFERRED"),
            ("AWS", "PREFERRED"),
            ("CI/CD", "PREFERRED"),
        ],
    },
    {
        "key": "frontend",
        "company": "northwind",
        "title": "Frontend Engineer",
        "department": "Product",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "REMOTE",
        "salary": (70000, 95000),
        "min_exp": 3,
        "max_exp": 8,
        "level": "MID",
        "education": None,
        "status": "PUBLISHED",
        "days_ago": 14,
        "deadline_days": 30,
        "hiring_manager": "hiring.manager@demo.example",
        "description": "Build the interfaces developers use every day. You will craft accessible, fast React and TypeScript applications and "
        "work closely with design and backend engineers.",
        "responsibilities": "Develop responsive UIs with React, TypeScript and Tailwind CSS. Own component libraries, accessibility and performance. Write tests.",
        "qualifications": "3+ years of professional frontend development. Strong TypeScript. Eye for detail and accessibility.",
        "benefits": "Fully remote within the EU, home-office budget, flexible hours.",
        "skills": [
            ("React", "REQUIRED"),
            ("TypeScript", "REQUIRED"),
            ("Tailwind CSS", "REQUIRED"),
            ("HTML", "REQUIRED"),
            ("CSS", "REQUIRED"),
            ("Next.js", "PREFERRED"),
            ("Jest", "PREFERRED"),
        ],
    },
    {
        "key": "mle",
        "company": "northwind",
        "title": "Machine Learning Engineer",
        "department": "Applied AI",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (95000, 130000),
        "min_exp": 3,
        "max_exp": None,
        "level": "SENIOR",
        "education": "MASTER",
        "status": "PUBLISHED",
        "days_ago": 9,
        "deadline_days": 45,
        "hiring_manager": "hiring.manager@demo.example",
        "description": "Turn research into production. You will train, evaluate and deploy natural-language and ranking models that power search "
        "and recommendations in our products.",
        "responsibilities": "Build NLP and semantic search pipelines with PyTorch and Hugging Face. Design offline evaluation and A/B tests. "
        "Productionise models with MLOps best practices.",
        "qualifications": "3+ years applying machine learning. Master's degree or equivalent experience. Strong Python and statistics.",
        "benefits": "Conference budget, GPU access, hybrid work.",
        "skills": [
            ("Python", "REQUIRED"),
            ("Machine Learning", "REQUIRED"),
            ("PyTorch", "REQUIRED"),
            ("Natural Language Processing", "REQUIRED"),
            ("Statistics", "PREFERRED"),
            ("MLOps", "PREFERRED"),
            ("SQL", "PREFERRED"),
        ],
    },
    {
        "key": "devops",
        "company": "northwind",
        "title": "DevOps Engineer",
        "department": "Infrastructure",
        "location": "Munich, Germany",
        "employment": "FULL_TIME",
        "workplace": "ONSITE",
        "salary": (80000, 105000),
        "min_exp": 4,
        "max_exp": None,
        "level": "SENIOR",
        "education": None,
        "status": "PUBLISHED",
        "days_ago": 5,
        "deadline_days": 25,
        "hiring_manager": None,
        "description": "Keep Northwind fast and reliable. You will run our Kubernetes platform, automate infrastructure as code and make deployments boring.",
        "responsibilities": "Operate Kubernetes clusters on AWS. Manage infrastructure with Terraform. Build CI/CD pipelines and observability with Prometheus and Grafana.",
        "qualifications": "4+ years in DevOps or SRE. Deep Linux knowledge. On-call experience.",
        "benefits": "Relocation support, on-call compensation.",
        "skills": [
            ("Kubernetes", "REQUIRED"),
            ("Terraform", "REQUIRED"),
            ("AWS", "REQUIRED"),
            ("CI/CD", "REQUIRED"),
            ("Linux", "REQUIRED"),
            ("Docker", "PREFERRED"),
            ("Prometheus", "PREFERRED"),
        ],
    },
    {
        "key": "analyst",
        "company": "northwind",
        "title": "Data Analyst",
        "department": "Business Intelligence",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (55000, 75000),
        "min_exp": 2,
        "max_exp": 6,
        "level": "MID",
        "education": "BACHELOR",
        "status": "PUBLISHED",
        "days_ago": 30,
        "deadline_days": 15,
        "hiring_manager": None,
        "description": "Help teams make decisions with data. You will build dashboards, analyse product usage and run experiments.",
        "responsibilities": "Write SQL, build Tableau dashboards, analyse funnels and retention, partner with product managers.",
        "qualifications": "2+ years in analytics. Strong SQL and Excel. Clear communication.",
        "benefits": "Hybrid work, learning budget.",
        "skills": [
            ("SQL", "REQUIRED"),
            ("Tableau", "REQUIRED"),
            ("Excel", "REQUIRED"),
            ("Statistics", "REQUIRED"),
            ("Python", "PREFERRED"),
            ("A/B Testing", "PREFERRED"),
        ],
    },
    {
        "key": "intern",
        "company": "northwind",
        "title": "Software Engineering Intern",
        "department": "Engineering",
        "location": "Berlin, Germany",
        "employment": "INTERNSHIP",
        "workplace": "ONSITE",
        "salary": (1800, 2200),
        "min_exp": 0,
        "max_exp": 1,
        "level": "ENTRY",
        "education": None,
        "status": "DRAFT",
        "days_ago": None,
        "deadline_days": 60,
        "hiring_manager": None,
        "description": "A six-month internship for students who want to learn how production software is built, reviewed and shipped.",
        "responsibilities": "Pair with senior engineers, ship small features, write tests.",
        "qualifications": "Currently studying computer science or a related field.",
        "benefits": "Mentorship, possibility of a full-time offer.",
        "skills": [("Python", "REQUIRED"), ("Git", "REQUIRED"), ("SQL", "PREFERRED")],
    },
    {
        "key": "platform",
        "company": "northwind",
        "title": "Platform Engineer",
        "department": "Platform",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (85000, 110000),
        "min_exp": 3,
        "max_exp": None,
        "level": "MID",
        "education": None,
        "status": "PAUSED",
        "days_ago": 40,
        "deadline_days": 20,
        "hiring_manager": "hiring.manager@demo.example",
        "description": "Paused while we re-plan the platform roadmap. Build internal developer platforms that make every team faster.",
        "responsibilities": "Build self-service tooling, golden paths and internal APIs.",
        "qualifications": "3+ years of backend or platform engineering.",
        "benefits": "Hybrid work.",
        "skills": [("Python", "REQUIRED"), ("Docker", "REQUIRED"), ("Kubernetes", "PREFERRED")],
    },
    {
        "key": "qa",
        "company": "northwind",
        "title": "QA Automation Engineer",
        "department": "Quality",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (60000, 80000),
        "min_exp": 3,
        "max_exp": None,
        "level": "MID",
        "education": None,
        "status": "CLOSED",
        "days_ago": 75,
        "deadline_days": None,
        "hiring_manager": "hiring.manager@demo.example",
        "description": "Closed after the position was filled. Own end-to-end and API test automation for the Northwind platform.",
        "responsibilities": "Build Playwright and Pytest suites, improve CI quality gates.",
        "qualifications": "3+ years in test automation.",
        "benefits": "Hybrid work.",
        "skills": [
            ("Pytest", "REQUIRED"),
            ("Playwright", "REQUIRED"),
            ("Python", "REQUIRED"),
            ("CI/CD", "PREFERRED"),
        ],
    },
    {
        "key": "legacy",
        "company": "northwind",
        "title": "Support Engineer (EMEA)",
        "department": "Customer Success",
        "location": "Berlin, Germany",
        "employment": "FULL_TIME",
        "workplace": "ONSITE",
        "salary": (45000, 58000),
        "min_exp": 1,
        "max_exp": None,
        "level": "JUNIOR",
        "education": None,
        "status": "ARCHIVED",
        "days_ago": 150,
        "deadline_days": None,
        "hiring_manager": None,
        "description": "Archived posting kept for reporting history.",
        "responsibilities": "Resolve customer technical issues.",
        "qualifications": "Customer-facing technical experience.",
        "benefits": None,
        "skills": [("Customer Support", "REQUIRED"), ("SQL", "PREFERRED")],
    },
    {
        "key": "icu_nurse",
        "company": "helio",
        "title": "Registered Nurse — ICU",
        "department": "Critical Care",
        "location": "Boston, USA",
        "employment": "FULL_TIME",
        "workplace": "ONSITE",
        "salary": (82000, 104000),
        "min_exp": 2,
        "max_exp": None,
        "level": "MID",
        "education": "BACHELOR",
        "status": "PUBLISHED",
        "days_ago": 12,
        "deadline_days": 35,
        "hiring_manager": None,
        "description": "Care for critically ill patients in our 24-bed intensive care unit as part of a collaborative multidisciplinary team.",
        "responsibilities": "Monitor and assess critically ill patients. Administer medications and document care in the EHR. Support families.",
        "qualifications": "Active RN licence. BLS and ACLS certification. 2+ years in critical care preferred.",
        "benefits": "Shift differentials, tuition support, retirement matching.",
        "skills": [
            ("Critical Care", "REQUIRED"),
            ("Patient Care", "REQUIRED"),
            ("BLS", "REQUIRED"),
            ("ACLS", "REQUIRED"),
            ("Electronic Health Records", "PREFERRED"),
            ("Medication Administration", "PREFERRED"),
        ],
    },
    {
        "key": "clin_analyst",
        "company": "helio",
        "title": "Clinical Data Analyst",
        "department": "Quality & Analytics",
        "location": "Boston, USA",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (70000, 90000),
        "min_exp": 2,
        "max_exp": None,
        "level": "MID",
        "education": "BACHELOR",
        "status": "PUBLISHED",
        "days_ago": 8,
        "deadline_days": 30,
        "hiring_manager": None,
        "description": "Turn clinical and operational data into insight that improves patient outcomes.",
        "responsibilities": "Build SQL pipelines over EHR data, create Power BI dashboards, support quality-improvement studies.",
        "qualifications": "2+ years of analytics, healthcare experience a plus.",
        "benefits": "Hybrid work, tuition support.",
        "skills": [
            ("SQL", "REQUIRED"),
            ("Power BI", "REQUIRED"),
            ("Statistics", "REQUIRED"),
            ("Electronic Health Records", "PREFERRED"),
            ("Python", "PREFERRED"),
        ],
    },
    {
        "key": "marketing_mgr",
        "company": "brightwave",
        "title": "Marketing Manager",
        "department": "Growth",
        "location": "London, United Kingdom",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (60000, 80000),
        "min_exp": 4,
        "max_exp": None,
        "level": "SENIOR",
        "education": "BACHELOR",
        "status": "PUBLISHED",
        "days_ago": 10,
        "deadline_days": 28,
        "hiring_manager": None,
        "description": "Lead Brightwave's own growth engine: content, SEO and paid acquisition for B2B software clients.",
        "responsibilities": "Own the content calendar and SEO strategy, manage paid campaigns, report on pipeline with Google Analytics.",
        "qualifications": "4+ years in B2B marketing. Proven SEO and content results.",
        "benefits": "Hybrid work, 28 days holiday.",
        "skills": [
            ("SEO", "REQUIRED"),
            ("Content Marketing", "REQUIRED"),
            ("Google Analytics", "REQUIRED"),
            ("Brand Management", "PREFERRED"),
            ("Email Marketing", "PREFERRED"),
        ],
    },
    {
        "key": "fin_analyst",
        "company": "orbit",
        "title": "Financial Analyst",
        "department": "Finance",
        "location": "Amsterdam, Netherlands",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (58000, 76000),
        "min_exp": 3,
        "max_exp": None,
        "level": "MID",
        "education": "BACHELOR",
        "status": "PUBLISHED",
        "days_ago": 6,
        "deadline_days": 21,
        "hiring_manager": None,
        "description": "Support Orbit's planning and forecasting cycle with rigorous financial analysis.",
        "responsibilities": "Build financial models, own monthly forecasting and budgeting, partner with business leads.",
        "qualifications": "3+ years in financial analysis. Advanced Excel and SQL.",
        "benefits": "Hybrid work, pension, learning budget.",
        "skills": [
            ("Financial Analysis", "REQUIRED"),
            ("Excel", "REQUIRED"),
            ("Budgeting", "REQUIRED"),
            ("SQL", "PREFERRED"),
        ],
    },
    {
        "key": "java_backend",
        "company": "orbit",
        "title": "Backend Engineer (Java)",
        "department": "Payments",
        "location": "Amsterdam, Netherlands",
        "employment": "FULL_TIME",
        "workplace": "HYBRID",
        "salary": (75000, 100000),
        "min_exp": 4,
        "max_exp": None,
        "level": "SENIOR",
        "education": None,
        "status": "PUBLISHED",
        "days_ago": 7,
        "deadline_days": 30,
        "hiring_manager": None,
        "description": "Build the low-latency payment services that move money for European fintechs.",
        "responsibilities": "Develop Spring Boot microservices, stream events with Kafka, operate PostgreSQL at scale.",
        "qualifications": "4+ years of Java backend development in distributed systems.",
        "benefits": "Hybrid work, pension.",
        "skills": [
            ("Java", "REQUIRED"),
            ("Spring Boot", "REQUIRED"),
            ("PostgreSQL", "REQUIRED"),
            ("Kafka", "REQUIRED"),
            ("Microservices", "PREFERRED"),
            ("Docker", "PREFERRED"),
        ],
    },
]

# Candidate cast. skills: (name, proficiency, years). experiences: (title, company, start_years_ago, end_years_ago|None, description)
CANDIDATES: list[dict[str, Any]] = [
    {
        "key": "alex",
        "email": "candidate@demo.example",
        "first": "Alex",
        "last": "Rivera",
        "searchable": True,
        "headline": "Senior Backend Engineer — Python, FastAPI & PostgreSQL",
        "location": "Berlin, Germany",
        "years": 5.5,
        "summary": "Backend engineer with 5+ years building high-throughput Python APIs. I design FastAPI services on PostgreSQL and Redis, containerise "
        "them with Docker and ship them through CI/CD to AWS. I care about reliability, clean data models and mentoring.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "TWO_WEEKS",
        "salary": 98000,
        "links": {
            "github": "https://github.com/alex-rivera",
            "linkedin": "https://www.linkedin.com/in/alex-rivera",
        },
        "skills": [
            ("Python", "EXPERT", 6),
            ("FastAPI", "ADVANCED", 3),
            ("PostgreSQL", "ADVANCED", 5),
            ("Redis", "ADVANCED", 4),
            ("Docker", "ADVANCED", 4),
            ("AWS", "INTERMEDIATE", 3),
            ("CI/CD", "ADVANCED", 4),
            ("SQLAlchemy", "ADVANCED", 4),
            ("REST APIs", "EXPERT", 5),
            ("Pytest", "ADVANCED", 4),
        ],
        "experiences": [
            (
                "Senior Backend Engineer",
                "Paylane",
                2.5,
                None,
                "Own the transactions API (FastAPI, PostgreSQL, Redis) serving 4k req/s. Introduced async workers, caching and "
                "query optimisation that cut p95 latency by 60%. Mentor three engineers and run the on-call rotation.",
            ),
            (
                "Backend Engineer",
                "Shipwise",
                5.5,
                2.5,
                "Built REST APIs in Python and Django, migrated to FastAPI, containerised services with Docker and set up GitHub Actions CI/CD on AWS.",
            ),
        ],
        "education": [("TU Berlin", "BACHELOR", "BSc Computer Science", "Computer Science", 2012, 2016)],
        "certifications": [("AWS Certified Developer – Associate", "Amazon Web Services")],
        "languages": [("English", "FLUENT"), ("German", "NATIVE")],
    },
    {
        "key": "elena",
        "email": "elena.fischer@demo.example",
        "first": "Elena",
        "last": "Fischer",
        "searchable": True,
        "headline": "Full-stack developer — Django, React, PostgreSQL",
        "location": "Hamburg, Germany",
        "years": 3.0,
        "summary": "Full-stack developer who enjoys backend work with Django and PostgreSQL and building React front-ends. Looking to deepen backend and cloud skills.",
        "remote": "FLEXIBLE",
        "employment": "FULL_TIME",
        "availability": "ONE_MONTH",
        "salary": 68000,
        "links": {"github": "https://github.com/elena-fischer"},
        "skills": [
            ("Python", "ADVANCED", 4),
            ("Django", "ADVANCED", 3),
            ("PostgreSQL", "INTERMEDIATE", 3),
            ("React", "INTERMEDIATE", 2),
            ("JavaScript", "INTERMEDIATE", 3),
            ("Git", "ADVANCED", 4),
            ("REST APIs", "ADVANCED", 3),
        ],
        "experiences": [
            (
                "Full-Stack Developer",
                "Webwerk",
                3.0,
                None,
                "Develop and maintain Django REST services and React dashboards for logistics clients. PostgreSQL schema design and reporting queries.",
            )
        ],
        "education": [("University of Hamburg", "BACHELOR", "BSc Informatics", "Informatics", 2014, 2018)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("German", "NATIVE")],
    },
    {
        "key": "gabe",
        "email": "gabe.okoye@demo.example",
        "first": "Gabe",
        "last": "Okoye",
        "searchable": True,
        "headline": "Java Backend Engineer — Spring Boot, Kafka, PostgreSQL",
        "location": "Amsterdam, Netherlands",
        "years": 6.5,
        "summary": "Java engineer with six years of experience in event-driven microservices. Spring Boot, Kafka and PostgreSQL in payment and logistics systems.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "ONE_MONTH",
        "salary": 92000,
        "links": {"linkedin": "https://www.linkedin.com/in/gabe-okoye"},
        "skills": [
            ("Java", "EXPERT", 7),
            ("Spring Boot", "ADVANCED", 5),
            ("PostgreSQL", "ADVANCED", 5),
            ("Kafka", "ADVANCED", 4),
            ("Docker", "INTERMEDIATE", 3),
            ("Microservices", "ADVANCED", 4),
            ("JUnit", "ADVANCED", 5),
        ],
        "experiences": [
            (
                "Senior Java Engineer",
                "FlowPay",
                3.5,
                None,
                "Designed event-driven payment microservices with Spring Boot and Kafka on PostgreSQL. Led migration from a monolith.",
            ),
            (
                "Java Developer",
                "Cargoline",
                6.5,
                3.5,
                "Built Spring Boot services and batch jobs for logistics tracking; PostgreSQL tuning and JUnit test suites.",
            ),
        ],
        "education": [
            (
                "University of Lagos",
                "BACHELOR",
                "BEng Computer Engineering",
                "Computer Engineering",
                2010,
                2015,
            )
        ],
        "certifications": [],
        "languages": [("English", "FLUENT")],
    },
    {
        "key": "farah",
        "email": "farah.khan@demo.example",
        "first": "Farah",
        "last": "Khan",
        "searchable": True,
        "headline": "Junior Backend Developer — Python & MySQL",
        "location": "Berlin, Germany",
        "years": 1.2,
        "summary": "Junior developer with a year of experience building small Flask APIs on MySQL. Eager to grow into a strong backend engineer.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "IMMEDIATELY",
        "salary": 48000,
        "links": {"github": "https://github.com/farah-khan"},
        "skills": [
            ("Python", "INTERMEDIATE", 2),
            ("Flask", "INTERMEDIATE", 1),
            ("MySQL", "INTERMEDIATE", 1),
            ("Git", "INTERMEDIATE", 2),
            ("HTML", "INTERMEDIATE", 2),
        ],
        "experiences": [
            (
                "Junior Backend Developer",
                "Brightbyte",
                1.2,
                None,
                "Maintain Flask APIs and MySQL queries for an internal CRM; write unit tests.",
            )
        ],
        "education": [("TU Dresden", "BACHELOR", "BSc Computer Science", "Computer Science", 2018, 2021)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Urdu", "NATIVE")],
    },
    {
        "key": "mateo",
        "email": "mateo.silva@demo.example",
        "first": "Mateo",
        "last": "Silva",
        "searchable": True,
        "headline": "Career changer into backend development — Python, FastAPI",
        "location": "Lisbon, Portugal",
        "years": 0.5,
        "summary": "Former project coordinator who completed an intensive backend bootcamp. Built FastAPI and PostgreSQL projects including a booking API with Docker.",
        "remote": "REMOTE",
        "employment": "FULL_TIME",
        "availability": "IMMEDIATELY",
        "salary": 42000,
        "links": {"github": "https://github.com/mateo-silva"},
        "skills": [
            ("Python", "INTERMEDIATE", 1),
            ("FastAPI", "INTERMEDIATE", 1),
            ("PostgreSQL", "BEGINNER", 1),
            ("Docker", "BEGINNER", 1),
            ("Git", "INTERMEDIATE", 2),
        ],
        "experiences": [
            (
                "Project Coordinator",
                "Atlantic Events",
                4.0,
                0.7,
                "Coordinated vendors and schedules for conferences. Automated reporting with spreadsheets.",
            ),
            (
                "Backend Developer (Bootcamp Project)",
                "Self-employed",
                0.7,
                None,
                "Built a booking REST API with FastAPI, PostgreSQL and Docker for the bootcamp capstone.",
            ),
        ],
        "education": [
            (
                "University of Lisbon",
                "BACHELOR",
                "BA Business Administration",
                "Business Administration",
                2013,
                2017,
            )
        ],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Portuguese", "NATIVE")],
    },
    {
        "key": "bianca",
        "email": "bianca.costa@demo.example",
        "first": "Bianca",
        "last": "Costa",
        "searchable": True,
        "headline": "Frontend Engineer — React, TypeScript, Tailwind",
        "location": "Berlin, Germany",
        "years": 4.5,
        "summary": "Frontend engineer focused on accessible, fast interfaces. React, TypeScript, Next.js and Tailwind CSS in SaaS products; design-system enthusiast.",
        "remote": "REMOTE",
        "employment": "FULL_TIME",
        "availability": "TWO_WEEKS",
        "salary": 82000,
        "links": {"github": "https://github.com/bianca-costa", "portfolio": "https://bianca.example.dev"},
        "skills": [
            ("React", "EXPERT", 5),
            ("TypeScript", "ADVANCED", 4),
            ("Next.js", "ADVANCED", 3),
            ("Tailwind CSS", "ADVANCED", 3),
            ("HTML", "EXPERT", 6),
            ("CSS", "EXPERT", 6),
            ("Jest", "ADVANCED", 4),
            ("Figma", "INTERMEDIATE", 3),
        ],
        "experiences": [
            (
                "Frontend Engineer",
                "Lumina SaaS",
                2.5,
                None,
                "Own the React and TypeScript front-end of a B2B analytics app. Built the Tailwind-based design system, improved Lighthouse scores and accessibility to WCAG AA.",
            ),
            (
                "Web Developer",
                "Pixelhaus",
                4.5,
                2.5,
                "Delivered responsive marketing sites and React widgets; Jest unit tests.",
            ),
        ],
        "education": [
            ("Humboldt University", "BACHELOR", "BA Media Informatics", "Media Informatics", 2013, 2017)
        ],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Portuguese", "NATIVE"), ("German", "CONVERSATIONAL")],
    },
    {
        "key": "chen",
        "email": "chen.wei@demo.example",
        "first": "Chen",
        "last": "Wei",
        "searchable": True,
        "headline": "Machine Learning Engineer — NLP & Semantic Search",
        "location": "Berlin, Germany",
        "years": 6.0,
        "summary": "ML engineer with six years of experience in natural language processing, embeddings and ranking. I train models in PyTorch, evaluate them rigorously and "
        "ship them with MLOps pipelines. MSc in Computer Science.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "ONE_MONTH",
        "salary": 115000,
        "links": {
            "github": "https://github.com/chen-wei",
            "linkedin": "https://www.linkedin.com/in/chen-wei",
        },
        "skills": [
            ("Python", "EXPERT", 8),
            ("Machine Learning", "EXPERT", 6),
            ("PyTorch", "ADVANCED", 5),
            ("Natural Language Processing", "EXPERT", 5),
            ("Hugging Face", "ADVANCED", 3),
            ("Pandas", "ADVANCED", 6),
            ("SQL", "ADVANCED", 5),
            ("Statistics", "ADVANCED", 6),
            ("MLOps", "INTERMEDIATE", 3),
            ("Semantic Search", "ADVANCED", 3),
        ],
        "experiences": [
            (
                "Senior ML Engineer",
                "Searchly",
                3.0,
                None,
                "Built semantic search and learning-to-rank for an e-commerce platform: transformer embeddings, vector retrieval, offline evaluation and A/B tests.",
            ),
            (
                "Data Scientist",
                "Finlytics",
                6.0,
                3.0,
                "Trained NLP classifiers in PyTorch for document processing; statistical analysis and experimentation.",
            ),
        ],
        "education": [("TU Munich", "MASTER", "MSc Computer Science", "Computer Science", 2014, 2016)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Mandarin", "NATIVE"), ("German", "CONVERSATIONAL")],
    },
    {
        "key": "dmitri",
        "email": "dmitri.volkov@demo.example",
        "first": "Dmitri",
        "last": "Volkov",
        "searchable": True,
        "headline": "DevOps / SRE Engineer — Kubernetes, Terraform, AWS",
        "location": "Munich, Germany",
        "years": 7.0,
        "summary": "Site reliability engineer running Kubernetes platforms on AWS. Terraform, CI/CD, observability with Prometheus and Grafana, and a calm approach to on-call.",
        "remote": "ONSITE",
        "employment": "FULL_TIME",
        "availability": "ONE_MONTH",
        "salary": 100000,
        "links": {"linkedin": "https://www.linkedin.com/in/dmitri-volkov"},
        "skills": [
            ("Kubernetes", "EXPERT", 5),
            ("Terraform", "ADVANCED", 5),
            ("AWS", "EXPERT", 6),
            ("Docker", "EXPERT", 7),
            ("CI/CD", "ADVANCED", 6),
            ("Linux", "EXPERT", 9),
            ("Prometheus", "ADVANCED", 4),
            ("Grafana", "ADVANCED", 4),
            ("Python", "INTERMEDIATE", 4),
            ("Ansible", "ADVANCED", 4),
        ],
        "experiences": [
            (
                "Senior DevOps Engineer",
                "Cloudhaus",
                3.5,
                None,
                "Operate multi-region Kubernetes clusters on AWS, codified with Terraform. Built GitOps CI/CD pipelines and Prometheus/Grafana alerting.",
            ),
            (
                "Systems Administrator",
                "Datanet",
                7.0,
                3.5,
                "Linux administration, Ansible automation, containerisation with Docker, migration to AWS.",
            ),
        ],
        "education": [
            (
                "Bauman Moscow State Technical University",
                "BACHELOR",
                "BSc Information Systems",
                "Information Systems",
                2011,
                2015,
            )
        ],
        "certifications": [
            ("Certified Kubernetes Administrator", "CNCF"),
            ("AWS Certified Solutions Architect – Associate", "Amazon Web Services"),
        ],
        "languages": [("English", "FLUENT"), ("Russian", "NATIVE")],
    },
    {
        "key": "hana",
        "email": "hana.sato@demo.example",
        "first": "Hana",
        "last": "Sato",
        "searchable": True,
        "headline": "Data Analyst — SQL, Tableau, Excel",
        "location": "Berlin, Germany",
        "years": 3.5,
        "summary": "Analyst turning product and marketing data into decisions. Advanced SQL, Tableau dashboards, Excel modelling, and experiment analysis.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "TWO_WEEKS",
        "salary": 62000,
        "links": {"linkedin": "https://www.linkedin.com/in/hana-sato"},
        "skills": [
            ("SQL", "EXPERT", 5),
            ("Tableau", "ADVANCED", 3),
            ("Excel", "ADVANCED", 5),
            ("Statistics", "INTERMEDIATE", 3),
            ("Python", "INTERMEDIATE", 2),
            ("A/B Testing", "INTERMEDIATE", 2),
            ("Data Analysis", "ADVANCED", 4),
        ],
        "experiences": [
            (
                "Data Analyst",
                "Shopwave",
                3.5,
                None,
                "Built Tableau dashboards for growth and retention, wrote SQL for funnel analysis and designed A/B tests with product managers.",
            )
        ],
        "education": [("Freie Universität Berlin", "BACHELOR", "BSc Economics", "Economics", 2014, 2018)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Japanese", "NATIVE"), ("German", "CONVERSATIONAL")],
    },
    {
        "key": "julia",
        "email": "julia.martins@demo.example",
        "first": "Julia",
        "last": "Martins",
        "searchable": True,
        "headline": "Registered Nurse — Intensive Care",
        "location": "Boston, USA",
        "years": 8.0,
        "summary": "ICU registered nurse with eight years of critical-care experience: ventilated patients, haemodynamic monitoring, rapid response and family communication.",
        "remote": "ONSITE",
        "employment": "FULL_TIME",
        "availability": "ONE_MONTH",
        "salary": 96000,
        "links": {},
        "skills": [
            ("Critical Care", "EXPERT", 8),
            ("Patient Care", "EXPERT", 8),
            ("BLS", "EXPERT", 8),
            ("ACLS", "ADVANCED", 6),
            ("Electronic Health Records", "ADVANCED", 6),
            ("Medication Administration", "EXPERT", 8),
        ],
        "experiences": [
            (
                "ICU Registered Nurse",
                "St. Anne's Hospital",
                8.0,
                None,
                "Care for ventilated and post-operative patients in a 20-bed ICU; manage medication administration, document in Epic EHR and respond to rapid-response calls.",
            )
        ],
        "education": [("Boston College", "BACHELOR", "BSN Nursing", "Nursing", 2012, 2016)],
        "certifications": [
            ("Advanced Cardiac Life Support (ACLS)", "American Heart Association"),
            ("Basic Life Support (BLS)", "American Heart Association"),
        ],
        "languages": [("English", "NATIVE"), ("Portuguese", "FLUENT")],
    },
    {
        "key": "kofi",
        "email": "kofi.mensah@demo.example",
        "first": "Kofi",
        "last": "Mensah",
        "searchable": True,
        "headline": "B2B Marketing Manager — SEO & Content",
        "location": "London, United Kingdom",
        "years": 6.0,
        "summary": "Growth-minded marketer who has scaled organic traffic for SaaS companies through SEO, content marketing and analytics-led experimentation.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "ONE_MONTH",
        "salary": 72000,
        "links": {"linkedin": "https://www.linkedin.com/in/kofi-mensah"},
        "skills": [
            ("SEO", "EXPERT", 6),
            ("Content Marketing", "EXPERT", 6),
            ("Google Analytics", "ADVANCED", 5),
            ("Brand Management", "INTERMEDIATE", 3),
            ("Email Marketing", "ADVANCED", 4),
            ("Copywriting", "ADVANCED", 5),
        ],
        "experiences": [
            (
                "Marketing Manager",
                "Stackpath Media",
                3.0,
                None,
                "Lead SEO and content for a SaaS portfolio: tripled organic sign-ups, managed freelancers, reported weekly in Google Analytics.",
            ),
            (
                "Content Marketer",
                "Greenfield Digital",
                6.0,
                3.0,
                "Wrote long-form content, ran email campaigns, built keyword strategy.",
            ),
        ],
        "education": [("University of Leeds", "BACHELOR", "BA Marketing", "Marketing", 2013, 2016)],
        "certifications": [("Google Analytics Certification", "Google")],
        "languages": [("English", "NATIVE")],
    },
    {
        "key": "lena",
        "email": "lena.vos@demo.example",
        "first": "Lena",
        "last": "Vos",
        "searchable": True,
        "headline": "Financial Analyst — Forecasting & Modelling",
        "location": "Amsterdam, Netherlands",
        "years": 4.0,
        "summary": "Financial analyst with four years in fintech: budgeting, forecasting and variance analysis with advanced Excel and SQL.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "TWO_WEEKS",
        "salary": 64000,
        "links": {},
        "skills": [
            ("Financial Analysis", "ADVANCED", 4),
            ("Excel", "EXPERT", 6),
            ("Budgeting", "ADVANCED", 4),
            ("SQL", "INTERMEDIATE", 3),
            ("Accounting", "INTERMEDIATE", 3),
        ],
        "experiences": [
            (
                "Financial Analyst",
                "Paynext",
                4.0,
                None,
                "Own monthly forecasting and budget tracking; built Excel/SQL models and presented variances to the CFO.",
            )
        ],
        "education": [("University of Amsterdam", "MASTER", "MSc Finance", "Finance", 2015, 2017)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Dutch", "NATIVE")],
    },
    {
        "key": "nina",
        "email": "nina.petrova@demo.example",
        "first": "Nina",
        "last": "Petrova",
        "searchable": True,
        "headline": "Staff Backend Engineer — Python, Go, Kubernetes",
        "location": "Vienna, Austria",
        "years": 11.0,
        "summary": "Staff engineer with eleven years of backend experience in Python and Go. Distributed systems, PostgreSQL internals, Kubernetes and engineering leadership.",
        "remote": "REMOTE",
        "employment": "FULL_TIME",
        "availability": "THREE_MONTHS",
        "salary": 125000,
        "links": {"github": "https://github.com/nina-petrova"},
        "skills": [
            ("Python", "EXPERT", 11),
            ("Go", "ADVANCED", 5),
            ("PostgreSQL", "EXPERT", 9),
            ("Kubernetes", "ADVANCED", 5),
            ("Docker", "EXPERT", 8),
            ("Redis", "ADVANCED", 7),
            ("AWS", "ADVANCED", 6),
            ("System Design", "EXPERT", 8),
            ("Leadership", "ADVANCED", 4),
            ("FastAPI", "ADVANCED", 3),
        ],
        "experiences": [
            (
                "Staff Engineer",
                "Datastream",
                4.0,
                None,
                "Architect high-volume event ingestion in Python and Go on Kubernetes; PostgreSQL partitioning and replication; lead a team of eight.",
            ),
            (
                "Senior Backend Engineer",
                "Mapwise",
                11.0,
                4.0,
                "Built geospatial APIs in Python, tuned PostgreSQL and Redis caching, Docker-based deployments.",
            ),
        ],
        "education": [("TU Wien", "MASTER", "MSc Software Engineering", "Software Engineering", 2008, 2013)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("German", "FLUENT"), ("Russian", "NATIVE")],
    },
    {
        "key": "oscar",
        "email": "oscar.lindqvist@demo.example",
        "first": "Oscar",
        "last": "Lindqvist",
        "searchable": True,
        "headline": "QA Automation Engineer — Pytest, Playwright",
        "location": "Berlin, Germany",
        "years": 4.0,
        "summary": "QA automation engineer building API and end-to-end test suites in Python with Pytest and Playwright, wired into CI.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "IMMEDIATELY",
        "salary": 66000,
        "links": {"github": "https://github.com/oscar-l"},
        "skills": [
            ("Pytest", "EXPERT", 4),
            ("Playwright", "ADVANCED", 2),
            ("Selenium", "ADVANCED", 3),
            ("Python", "ADVANCED", 5),
            ("CI/CD", "ADVANCED", 4),
            ("Test Automation", "EXPERT", 4),
        ],
        "experiences": [
            (
                "QA Automation Engineer",
                "Qualio",
                4.0,
                None,
                "Own API and UI test automation with Pytest and Playwright; quality gates in GitHub Actions.",
            )
        ],
        "education": [
            (
                "KTH Royal Institute of Technology",
                "BACHELOR",
                "BSc Information Technology",
                "Information Technology",
                2013,
                2016,
            )
        ],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Swedish", "NATIVE")],
    },
    {
        "key": "priya",
        "email": "priya.nair@demo.example",
        "first": "Priya",
        "last": "Nair",
        "searchable": True,
        "headline": "Data Scientist — Experimentation & NLP",
        "location": "Berlin, Germany",
        "years": 3.0,
        "summary": "Data scientist with a statistics background. I build NLP classifiers, run experiments and communicate results to non-technical stakeholders.",
        "remote": "HYBRID",
        "employment": "FULL_TIME",
        "availability": "TWO_WEEKS",
        "salary": 78000,
        "links": {"github": "https://github.com/priya-nair"},
        "skills": [
            ("Python", "ADVANCED", 4),
            ("Machine Learning", "ADVANCED", 3),
            ("Natural Language Processing", "INTERMEDIATE", 2),
            ("Statistics", "ADVANCED", 5),
            ("scikit-learn", "ADVANCED", 3),
            ("Pandas", "ADVANCED", 4),
            ("SQL", "ADVANCED", 4),
            ("A/B Testing", "ADVANCED", 3),
        ],
        "experiences": [
            (
                "Data Scientist",
                "Clickstream",
                3.0,
                None,
                "Built text classifiers with scikit-learn and PyTorch, designed experiments, productionised a churn model.",
            )
        ],
        "education": [("University of Edinburgh", "MASTER", "MSc Statistics", "Statistics", 2016, 2018)],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Hindi", "NATIVE")],
    },
    {
        "key": "tomas",
        "email": "tomas.novak@demo.example",
        "first": "Tomáš",
        "last": "Novák",
        "searchable": False,
        "headline": "Backend Engineer — Python (not open to recruiters)",
        "location": "Prague, Czechia",
        "years": 5.0,
        "summary": "Backend engineer happily employed; profile kept private from recruiter search.",
        "remote": "REMOTE",
        "employment": "FULL_TIME",
        "availability": "NOT_AVAILABLE",
        "salary": 90000,
        "links": {},
        "skills": [
            ("Python", "ADVANCED", 6),
            ("FastAPI", "ADVANCED", 3),
            ("PostgreSQL", "ADVANCED", 5),
            ("Docker", "ADVANCED", 5),
            ("Redis", "INTERMEDIATE", 3),
        ],
        "experiences": [
            ("Backend Engineer", "Praguesoft", 5.0, None, "Python and FastAPI services on PostgreSQL.")
        ],
        "education": [
            ("Czech Technical University", "BACHELOR", "BSc Informatics", "Informatics", 2012, 2016)
        ],
        "certifications": [],
        "languages": [("English", "FLUENT"), ("Czech", "NATIVE")],
    },
]

# Applications: (candidate, job, final status path through the workflow, days_after_publish_applied)
APPLICATIONS: list[dict[str, Any]] = [
    {
        "cand": "alex",
        "job": "backend",
        "path": ["SCREENING", "SHORTLISTED", "INTERVIEW"],
        "cover": "I have shipped FastAPI + PostgreSQL services at scale and would love to bring that to Northwind.",
    },
    {
        "cand": "elena",
        "job": "backend",
        "path": ["SCREENING"],
        "cover": "I'm keen to move deeper into backend and cloud work.",
    },
    {"cand": "gabe", "job": "backend", "path": []},
    {
        "cand": "farah",
        "job": "backend",
        "path": ["SCREENING", "REJECTED"],
        "reject": "Below the experience bar for this senior role; encouraged to re-apply to a junior opening.",
    },
    {"cand": "mateo", "job": "backend", "path": []},
    {"cand": "nina", "job": "backend", "path": ["SCREENING", "SHORTLISTED"]},
    {"cand": "oscar", "job": "backend", "path": [], "withdraw": True},
    {"cand": "bianca", "job": "frontend", "path": ["SCREENING", "SHORTLISTED", "INTERVIEW", "OFFER"]},
    {"cand": "elena", "job": "frontend", "path": []},
    {"cand": "chen", "job": "mle", "path": ["SCREENING", "SHORTLISTED"]},
    {"cand": "priya", "job": "mle", "path": ["SCREENING"]},
    {"cand": "dmitri", "job": "devops", "path": ["SCREENING"]},
    {"cand": "hana", "job": "analyst", "path": ["SCREENING", "SHORTLISTED", "INTERVIEW", "OFFER", "HIRED"]},
    {"cand": "priya", "job": "analyst", "path": []},
    {"cand": "oscar", "job": "qa", "path": ["SCREENING", "SHORTLISTED", "INTERVIEW", "OFFER", "HIRED"]},
    {"cand": "julia", "job": "icu_nurse", "path": ["SCREENING", "SHORTLISTED"]},
    {"cand": "hana", "job": "clin_analyst", "path": []},
    {"cand": "kofi", "job": "marketing_mgr", "path": ["SCREENING"]},
    {"cand": "lena", "job": "fin_analyst", "path": ["SCREENING", "SHORTLISTED"]},
    {"cand": "gabe", "job": "java_backend", "path": ["SCREENING", "SHORTLISTED", "INTERVIEW"]},
]
