import {
  createBrowserRouter,
  createMemoryRouter,
  Outlet,
  ScrollRestoration,
  type RouteObject,
} from 'react-router-dom'
import { AdaptiveLayout } from '@/components/layout/AdaptiveLayout'
import { AppShell } from '@/components/layout/AppShell'
import { AuthLayout } from '@/components/layout/AuthLayout'
import { PageContainer } from '@/components/layout/PageContainer'
import { PublicLayout } from '@/components/layout/PublicLayout'
import { RequireAuth, RequireGuest } from '@/features/auth/components/RequireAuth'
import { SettingsLayout } from '@/features/settings/components/SettingsLayout'
import NotFoundPage from '@/pages/NotFoundPage'
import RouteError from '@/pages/RouteError'
import { lazyPage, NavigationProgress, roleSwitch } from './lazy'
import { patterns, paths } from './paths'

/**
 * THE ROUTE TABLE. Every URL in the product is declared here, once.
 *
 * Wave-2 engineers do NOT edit this file: each feature area already points at a page module
 *   src/features/<domain>/pages/<Name>Page.tsx   (default export)
 * Replace the contents of that module. See docs/frontend-conventions.md for the list.
 *
 * Guards:  <RequireAuth roles={[…]} permission="…" />  (403 page in place)   <RequireGuest />  (login/register)
 */

const STAFF = ['RECRUITER', 'HIRING_MANAGER', 'ADMIN'] as const

export const routes: RouteObject[] = [
  {
    element: (
      <>
        <NavigationProgress />
        <Outlet />
        <ScrollRestoration getKey={(location) => location.pathname} />
      </>
    ),
    errorElement: <RouteError />,
    children: [
      // --- Public marketing ---------------------------------------------------------------------------------
      {
        element: <PublicLayout />,
        children: [{ index: true, element: lazyPage(() => import('@/features/home/pages/HomePage')) }],
      },

      // --- Auth (guests only) -----------------------------------------------------------------------------
      {
        element: <RequireGuest />,
        children: [
          {
            element: <AuthLayout />,
            children: [
              { path: paths.login, element: lazyPage(() => import('@/features/auth/pages/LoginPage')) },
              { path: paths.register, element: lazyPage(() => import('@/features/auth/pages/RegisterPage')) },
              {
                path: paths.registerEmployer,
                element: lazyPage(() => import('@/features/auth/pages/RegisterEmployerPage')),
              },
            ],
          },
        ],
      },

      // --- Public but personalised: job search + detail (visitors: marketing layout, members: app shell) ----
      {
        element: <AdaptiveLayout />,
        children: [
          { path: '*', element: <NotFoundPage /> },
          {
            path: paths.jobs,
            element: (
              <PageContainer>
                <Outlet />
              </PageContainer>
            ),
            children: [
              { index: true, element: lazyPage(() => import('@/features/jobs/pages/JobSearchPage')) },
              {
                path: 'saved',
                element: <RequireAuth roles={['CANDIDATE']} />,
                children: [
                  { index: true, element: lazyPage(() => import('@/features/jobs/pages/SavedJobsPage')) },
                ],
              },
              { path: ':id', element: lazyPage(() => import('@/features/jobs/pages/JobDetailPage')) },
            ],
          },
        ],
      },

      // --- Signed-in application ---------------------------------------------------------------------------
      {
        element: <RequireAuth />,
        children: [
          {
            element: <AppShell />,
            children: [
              // Role-dispatched URLs (one path, one page per role)
              {
                path: paths.dashboard,
                element: roleSwitch({
                  CANDIDATE: () => import('@/features/dashboard/pages/CandidateDashboardPage'),
                  RECRUITER: () => import('@/features/dashboard/pages/RecruiterDashboardPage'),
                  HIRING_MANAGER: () => import('@/features/dashboard/pages/RecruiterDashboardPage'),
                  ADMIN: () => import('@/features/dashboard/pages/AdminDashboardPage'),
                }),
              },
              {
                path: paths.applications,
                element: roleSwitch({
                  CANDIDATE: () => import('@/features/applications/pages/MyApplicationsPage'),
                  RECRUITER: () => import('@/features/applications/pages/ApplicationsPage'),
                  HIRING_MANAGER: () => import('@/features/applications/pages/ApplicationsPage'),
                  ADMIN: () => import('@/features/applications/pages/ApplicationsPage'),
                }),
              },
              {
                path: patterns.application,
                element: lazyPage(() => import('@/features/applications/pages/ApplicationDetailPage')),
              },
              {
                path: paths.interviews,
                element: roleSwitch({
                  CANDIDATE: () => import('@/features/interviews/pages/MyInterviewsPage'),
                  RECRUITER: () => import('@/features/interviews/pages/InterviewsPage'),
                  HIRING_MANAGER: () => import('@/features/interviews/pages/InterviewsPage'),
                  ADMIN: () => import('@/features/interviews/pages/InterviewsPage'),
                }),
              },
              {
                path: patterns.interview,
                element: lazyPage(() => import('@/features/interviews/pages/InterviewDetailPage')),
              },

              // Notifications (all roles)
              {
                path: paths.notifications,
                element: lazyPage(() => import('@/features/notifications/pages/NotificationsPage')),
              },

              // Candidate-only
              {
                element: <RequireAuth roles={['CANDIDATE']} />,
                children: [
                  {
                    path: paths.recommended,
                    element: lazyPage(() => import('@/features/recommendations/pages/RecommendedJobsPage')),
                  },
                  {
                    path: paths.resume,
                    element: lazyPage(() => import('@/features/resumes/pages/ResumePage')),
                  },
                  {
                    path: paths.profile,
                    element: lazyPage(() => import('@/features/profile/pages/ProfilePage')),
                  },
                ],
              },

              // Staff (recruiter / hiring manager / admin)
              {
                element: <RequireAuth roles={STAFF} />,
                children: [
                  // Jobs management (mine)
                  {
                    path: paths.manageJobs,
                    element: lazyPage(() => import('@/features/jobs/pages/ManageJobsPage')),
                  },
                  {
                    element: <RequireAuth permission="manage_jobs" />,
                    children: [
                      {
                        path: paths.manageJobNew,
                        element: lazyPage(() => import('@/features/jobs/pages/JobFormPage')),
                      },
                      {
                        path: patterns.manageJobEdit,
                        element: lazyPage(() => import('@/features/jobs/pages/JobFormPage')),
                      },
                    ],
                  },
                  {
                    path: paths.candidates,
                    element: lazyPage(() => import('@/features/candidates/pages/CandidatesPage')),
                  },
                  {
                    path: patterns.candidate,
                    element: lazyPage(() => import('@/features/candidates/pages/CandidateDetailPage')),
                  },
                  {
                    path: paths.matching,
                    element: lazyPage(() => import('@/features/matching/pages/MatchingPage')),
                  },
                  {
                    path: patterns.matchingJob,
                    element: lazyPage(() => import('@/features/matching/pages/MatchingPage')),
                  },
                  {
                    element: <RequireAuth permission="view_reports" />,
                    children: [
                      {
                        path: paths.reports,
                        element: lazyPage(() => import('@/features/reports/pages/ReportsPage')),
                      },
                    ],
                  },
                ],
              },

              // Admin
              {
                element: <RequireAuth roles={['ADMIN']} />,
                children: [
                  {
                    path: paths.adminUsers,
                    element: lazyPage(() => import('@/features/admin/pages/UsersPage')),
                  },
                  {
                    path: paths.adminCompanies,
                    element: lazyPage(() => import('@/features/admin/pages/CompaniesPage')),
                  },
                  {
                    path: paths.adminSystem,
                    element: lazyPage(() => import('@/features/admin/pages/SystemMonitoringPage')),
                  },
                ],
              },

              // Settings (account: mine; company + team: wave 2)
              {
                path: paths.settings,
                element: <SettingsLayout />,
                children: [
                  {
                    index: true,
                    element: lazyPage(() => import('@/features/settings/pages/AccountSettingsPage')),
                  },
                  {
                    element: <RequireAuth permission="manage_own_company" />,
                    children: [
                      {
                        path: 'company',
                        element: lazyPage(() => import('@/features/company/pages/CompanySettingsPage')),
                      },
                      {
                        path: 'team',
                        element: lazyPage(() => import('@/features/company/pages/TeamSettingsPage')),
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
]

export const createAppRouter = () => createBrowserRouter(routes)

/** For tests: the real route table on an in-memory history. */
export const createTestRouter = (initialEntries: string[]) => createMemoryRouter(routes, { initialEntries })
