"""Small word lists used by the résumé parser (kept apart from the parsing logic so both stay readable).

They are *heuristic aids*, not exhaustive dictionaries: a miss means the parser returns ``None`` for that field instead
of guessing, which is the intended failure mode.
"""

from __future__ import annotations

# --- section headings -------------------------------------------------------------------------------------------
# normalised heading text (lower case, letters / "&" / spaces only) -> section key
SECTION_ALIASES: dict[str, str] = {}


def _alias(key: str, *names: str) -> None:
    for n in names:
        SECTION_ALIASES[n] = key


_alias(
    "summary",
    "summary",
    "professional summary",
    "executive summary",
    "career summary",
    "summary of qualifications",
    "profile",
    "professional profile",
    "personal profile",
    "career profile",
    "objective",
    "career objective",
    "professional objective",
    "about me",
    "about",
    "overview",
    "professional overview",
)
_alias(
    "experience",
    "experience",
    "work experience",
    "professional experience",
    "employment",
    "employment history",
    "work history",
    "career history",
    "relevant experience",
    "professional background",
    "employment experience",
    "clinical experience",
    "industry experience",
    "experience & projects",
    "internships",
    "internship experience",
    "career experience",
    "work & experience",
    "working experience",
    "job history",
)
_alias(
    "education",
    "education",
    "education & training",
    "academic background",
    "academic qualifications",
    "education & qualifications",
    "academics",
    "educational background",
    "academic history",
    "education & certifications",
    "academic education",
)
_alias(
    "skills",
    "skills",
    "technical skills",
    "key skills",
    "core skills",
    "core competencies",
    "competencies",
    "technologies",
    "tech stack",
    "technical proficiencies",
    "skills & tools",
    "skills & technologies",
    "areas of expertise",
    "expertise",
    "tools & technologies",
    "technical expertise",
    "professional skills",
    "skills summary",
    "skills & expertise",
    "technical skills & tools",
    "tools",
    "technical summary",
    "skill set",
    "skillset",
    "clinical skills",
    "skills & competencies",
    "technical competencies",
    "relevant skills",
    "additional skills",
)
_alias(
    "certifications",
    "certifications",
    "certificates",
    "licenses",
    "licences",
    "licenses & certifications",
    "certifications & licenses",
    "licences & certifications",
    "professional certifications",
    "credentials",
    "licensure",
    "certification",
    "certifications & training",
    "licenses & credentials",
    "professional licenses",
    "certificates & licenses",
)
_alias(
    "languages",
    "languages",
    "language skills",
    "language proficiency",
    "spoken languages",
    "foreign languages",
)
_alias(
    "projects",
    "projects",
    "personal projects",
    "selected projects",
    "key projects",
    "open source",
    "open source contributions",
    "side projects",
    "academic projects",
    "notable projects",
    "project experience",
)
# recognised headings whose content is not parsed into structured data (but is still mined for skills)
_alias("other", "qualifications", "key qualifications", "highlights", "career highlights", "key achievements")
# sections that must END the previous one but whose content is not parsed (and never mined for skills)
_alias(
    "ignored",
    "awards",
    "honors",
    "honours",
    "awards & honors",
    "honors & awards",
    "publications",
    "interests",
    "hobbies",
    "hobbies & interests",
    "references",
    "volunteer",
    "volunteering",
    "volunteer experience",
    "volunteer work",
    "activities",
    "extracurricular activities",
    "achievements",
    "additional information",
    "personal details",
    "personal information",
    "personal data",
    "contact",
    "contact information",
    "contact details",
    "declaration",
    "patents",
    "affiliations",
    "memberships",
    "professional affiliations",
    "courses",
    "training",
    "additional",
    "other",
    "miscellaneous",
    "community involvement",
    "leadership & activities",
    "presentations",
    "speaking",
    "social",
    "links",
    "social links",
)

# Sections whose text is excluded from skill mining (personal or irrelevant content).
SKILL_EXCLUDED_SECTIONS = frozenset({"ignored"})


def _words(block: str) -> frozenset[str]:
    return frozenset(block.split())


# --- job-title vocabulary -------------------------------------------------------------------------------------
TITLE_WORDS = _words(
    """
    engineer engineers developer developers programmer architect manager director lead head analyst scientist consultant
    specialist administrator coordinator assistant associate officer executive designer nurse technician technologist
    therapist pharmacist physician doctor surgeon teacher lecturer professor instructor tutor accountant auditor controller
    recruiter representative agent supervisor intern trainee apprentice fellow researcher strategist planner buyer clerk
    cashier receptionist secretary driver operator mechanic electrician chef cook writer editor producer journalist marketer
    vp cto ceo cfo coo cio founder co-founder cofounder owner president partner principal staff senior junior sr jr tester
    qa sdet devops sre dba paramedic midwife caregiver paralegal attorney lawyer counsel advisor adviser freelancer
    contractor volunteer generalist practitioner sales merchandiser stylist barista bartender server host cleaner
    """
)
COMPANY_SUFFIXES = _words(
    """
    inc inc. llc ltd ltd. limited gmbh ag corp corp. corporation company co co. plc sa srl bv nv pty technologies
    technology systems labs lab group solutions university college hospital clinic bank partners holdings consulting
    industries software services studio studios agency institute school foundation authority association
    """
)
INSTITUTION_WORDS = (
    "university",
    "college",
    "institute",
    "school",
    "academy",
    "polytechnic",
    "universität",
    "universite",
    "université",
    "universidad",
    "università",
    "hochschule",
    "conservatory",
    "faculty",
)

# --- places ------------------------------------------------------------------------------------------------------
COUNTRIES = frozenset(
    c.lower()
    for c in (
        "United States",
        "USA",
        "US",
        "U.S.",
        "U.S.A.",
        "United Kingdom",
        "UK",
        "U.K.",
        "England",
        "Scotland",
        "Wales",
        "Northern Ireland",
        "Ireland",
        "Canada",
        "Australia",
        "New Zealand",
        "Germany",
        "France",
        "Spain",
        "Italy",
        "Portugal",
        "Netherlands",
        "Belgium",
        "Luxembourg",
        "Switzerland",
        "Austria",
        "Sweden",
        "Norway",
        "Denmark",
        "Finland",
        "Iceland",
        "Poland",
        "Czech Republic",
        "Czechia",
        "Slovakia",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Greece",
        "Croatia",
        "Serbia",
        "Slovenia",
        "Ukraine",
        "Russia",
        "Turkey",
        "Türkiye",
        "Israel",
        "Egypt",
        "Morocco",
        "Tunisia",
        "Algeria",
        "Nigeria",
        "Ghana",
        "Kenya",
        "South Africa",
        "Ethiopia",
        "Saudi Arabia",
        "KSA",
        "UAE",
        "United Arab Emirates",
        "Qatar",
        "Kuwait",
        "Bahrain",
        "Oman",
        "Jordan",
        "Lebanon",
        "Iraq",
        "Pakistan",
        "India",
        "Bangladesh",
        "Sri Lanka",
        "Nepal",
        "China",
        "Hong Kong",
        "Taiwan",
        "Japan",
        "South Korea",
        "Korea",
        "Singapore",
        "Malaysia",
        "Indonesia",
        "Thailand",
        "Vietnam",
        "Philippines",
        "Mexico",
        "Brazil",
        "Argentina",
        "Chile",
        "Colombia",
        "Peru",
        "Uruguay",
        "Estonia",
        "Latvia",
        "Lithuania",
        "Cyprus",
        "Malta",
    )
)
US_STATES = frozenset(
    s.lower()
    for s in (
        "AL",
        "AK",
        "AZ",
        "AR",
        "CA",
        "CO",
        "CT",
        "DE",
        "FL",
        "GA",
        "HI",
        "ID",
        "IL",
        "IN",
        "IA",
        "KS",
        "KY",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "MN",
        "MS",
        "MO",
        "MT",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VT",
        "VA",
        "WA",
        "WV",
        "WI",
        "WY",
        "DC",
        "ON",
        "BC",
        "AB",
        "QC",
        "NS",
        "MB",
        "SK",
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
        "Ontario",
        "British Columbia",
        "Alberta",
        "Quebec",
    )
)

# --- spoken languages -----------------------------------------------------------------------------------------
SPOKEN_LANGUAGES = {
    name.lower(): name
    for name in (
        "English",
        "Spanish",
        "French",
        "German",
        "Italian",
        "Portuguese",
        "Dutch",
        "Swedish",
        "Norwegian",
        "Danish",
        "Finnish",
        "Polish",
        "Czech",
        "Slovak",
        "Hungarian",
        "Romanian",
        "Bulgarian",
        "Greek",
        "Croatian",
        "Serbian",
        "Slovenian",
        "Ukrainian",
        "Russian",
        "Turkish",
        "Hebrew",
        "Arabic",
        "Persian",
        "Farsi",
        "Urdu",
        "Hindi",
        "Bengali",
        "Punjabi",
        "Tamil",
        "Telugu",
        "Marathi",
        "Gujarati",
        "Malayalam",
        "Kannada",
        "Nepali",
        "Sinhala",
        "Mandarin",
        "Cantonese",
        "Chinese",
        "Japanese",
        "Korean",
        "Vietnamese",
        "Thai",
        "Indonesian",
        "Malay",
        "Tagalog",
        "Filipino",
        "Swahili",
        "Amharic",
        "Hausa",
        "Yoruba",
        "Afrikaans",
        "Catalan",
        "Latin",
        "Estonian",
        "Latvian",
        "Lithuanian",
        "Icelandic",
        "Irish",
        "Welsh",
        "Albanian",
        "Armenian",
        "Georgian",
        "Kurdish",
        "Pashto",
    )
}

PROFICIENCY_WORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "NATIVE",
        (
            "native",
            "mother tongue",
            "mother-tongue",
            "first language",
            "bilingual",
            "native or bilingual",
            "c2 native",
        ),
    ),
    (
        "FLUENT",
        (
            "fluent",
            "full professional",
            "professional working",
            "proficient",
            "advanced",
            "c1",
            "c2",
            "excellent",
            "business fluent",
            "professional proficiency",
            "full fluency",
            "very good",
        ),
    ),
    (
        "CONVERSATIONAL",
        (
            "conversational",
            "intermediate",
            "upper intermediate",
            "upper-intermediate",
            "limited working",
            "working proficiency",
            "b1",
            "b2",
            "good",
            "working knowledge",
            "business",
        ),
    ),
    (
        "BASIC",
        ("basic", "beginner", "elementary", "a1", "a2", "limited", "some", "novice", "survival", "learning"),
    ),
)

MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

# Categories of personal data the parser must never extract (documented; asserted in tests against parser output).
PROTECTED_LABELS = (
    "date of birth",
    "dob",
    "birth date",
    "birthday",
    "age",
    "gender",
    "sex",
    "marital status",
    "nationality",
    "religion",
    "race",
    "ethnicity",
    "photo",
    "passport",
    "visa status",
    "children",
    "disability",
)
