"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 19:37:45.916681
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Enum('1-10', '11-50', '51-200', '201-1000', '1000+', name='company_size', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='company_status', native_enum=False, create_constraint=False), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("size IN ('1-10', '11-50', '51-200', '201-1000', '1000+')", name=op.f('ck_companies_company_size')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED')", name=op.f('ck_companies_company_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_index('uq_companies_name_lower', 'companies', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_skills_normalized_name'))
    )
    op.create_index('ix_skills_family', 'skills', ['family'], unique=False)
    op.create_index('ix_skills_name_trgm', 'skills', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('skill_aliases',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('display_alias', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_aliases_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_aliases')),
    sa.UniqueConstraint('alias', name=op.f('uq_skill_aliases_alias'))
    )
    op.create_index(op.f('ix_skill_aliases_skill_id'), 'skill_aliases', ['skill_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'HIRING_MANAGER', 'CANDIDATE', name='user_role', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='user_status', native_enum=False, create_constraint=False), server_default='ACTIVE', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role <> 'CANDIDATE' OR company_id IS NULL", name=op.f('ck_users_candidate_no_company')),
    sa.CheckConstraint("role IN ('ADMIN', 'RECRUITER', 'HIRING_MANAGER', 'CANDIDATE')", name=op.f('ck_users_user_role')),
    sa.CheckConstraint("role NOT IN ('RECRUITER', 'HIRING_MANAGER') OR company_id IS NOT NULL", name=op.f('ck_users_staff_company')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED')", name=op.f('ck_users_user_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_events_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_company_created', 'audit_events', ['company_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_events_created', 'audit_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('background_tasks',
    sa.Column('type', sa.Enum('PROCESS_RESUME', 'MATCH_JOB', 'MATCH_CANDIDATE', 'REFRESH_EMBEDDINGS', 'BULK_RESUME_IMPORT', 'EXPORT_REPORT', name='task_type', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='task_status', native_enum=False, create_constraint=False), server_default='PENDING', nullable=False),
    sa.Column('progress', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')", name=op.f('ck_background_tasks_task_status')),
    sa.CheckConstraint("type IN ('PROCESS_RESUME', 'MATCH_JOB', 'MATCH_CANDIDATE', 'REFRESH_EMBEDDINGS', 'BULK_RESUME_IMPORT', 'EXPORT_REPORT')", name=op.f('ck_background_tasks_task_type')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_background_tasks_progress_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_background_tasks_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_background_tasks_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_tasks'))
    )
    op.create_index('ix_background_tasks_creator', 'background_tasks', ['created_by_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_background_tasks_status_created', 'background_tasks', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_background_tasks_active_dedupe', 'background_tasks', ['dedupe_key'], unique=True, postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('PENDING', 'RUNNING')"))
    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('SELF', 'IMPORTED', name='candidate_source', native_enum=False, create_constraint=False), server_default='SELF', nullable=False),
    sa.Column('sourced_by_company_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=210), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('expected_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('remote_preference', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', 'FLEXIBLE', name='remote_preference', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('employment_preference', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY', name='candidate_employment_preference', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('availability', sa.Enum('IMMEDIATELY', 'TWO_WEEKS', 'ONE_MONTH', 'THREE_MONTHS', 'NOT_AVAILABLE', name='availability', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('is_searchable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('skills_text', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(display_name, '') || ' ' || coalesce(headline, '')), 'A') || setweight(to_tsvector('english', coalesce(skills_text, '')), 'A') || setweight(to_tsvector('english', coalesce(search_text, '')), 'C')", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_version', sa.String(length=20), nullable=True),
    sa.Column('embedding_source_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(user_id IS NOT NULL AND source = 'SELF') OR (user_id IS NULL AND source = 'IMPORTED' AND sourced_by_company_id IS NOT NULL)", name=op.f('ck_candidate_profiles_owner_consistent')),
    sa.CheckConstraint("availability IN ('IMMEDIATELY', 'TWO_WEEKS', 'ONE_MONTH', 'THREE_MONTHS', 'NOT_AVAILABLE')", name=op.f('ck_candidate_profiles_availability')),
    sa.CheckConstraint("employment_preference IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY')", name=op.f('ck_candidate_profiles_candidate_employment_preference')),
    sa.CheckConstraint("remote_preference IN ('ONSITE', 'HYBRID', 'REMOTE', 'FLEXIBLE')", name=op.f('ck_candidate_profiles_remote_preference')),
    sa.CheckConstraint("source IN ('SELF', 'IMPORTED')", name=op.f('ck_candidate_profiles_candidate_source')),
    sa.CheckConstraint('expected_salary IS NULL OR expected_salary >= 0', name=op.f('ck_candidate_profiles_expected_salary_positive')),
    sa.CheckConstraint('years_experience IS NULL OR (years_experience >= 0 AND years_experience <= 70)', name=op.f('ck_candidate_profiles_years_experience_range')),
    sa.ForeignKeyConstraint(['sourced_by_company_id'], ['companies.id'], name=op.f('fk_candidate_profiles_sourced_by_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidate_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_candidate_profiles_user_id'))
    )
    op.create_index('ix_candidate_profiles_display_name_trgm', 'candidate_profiles', ['display_name'], unique=False, postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_index('ix_candidate_profiles_embedding_hnsw', 'candidate_profiles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_candidate_profiles_location_trgm', 'candidate_profiles', ['location'], unique=False, postgresql_using='gin', postgresql_ops={'location': 'gin_trgm_ops'})
    op.create_index('ix_candidate_profiles_search_tsv', 'candidate_profiles', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_candidate_profiles_searchable', 'candidate_profiles', ['years_experience'], unique=False, postgresql_where=sa.text("is_searchable AND source = 'SELF'"))
    op.create_index(op.f('ix_candidate_profiles_sourced_by_company_id'), 'candidate_profiles', ['sourced_by_company_id'], unique=False)
    op.create_index('uq_candidate_profiles_company_email', 'candidate_profiles', ['sourced_by_company_id', sa.literal_column('lower(contact_email)')], unique=True, postgresql_where=sa.text("source = 'IMPORTED' AND contact_email IS NOT NULL"))
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('hiring_manager_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY', name='job_employment_type', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('workplace_type', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', name='job_workplace_type', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('min_experience_years', sa.Numeric(precision=4, scale=1), server_default='0', nullable=False),
    sa.Column('max_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('experience_level', sa.Enum('ENTRY', 'JUNIOR', 'MID', 'SENIOR', 'LEAD', name='experience_level', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('min_education_level', sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE', name='job_min_education_level', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PAUSED', 'CLOSED', 'ARCHIVED', name='job_status', native_enum=False, create_constraint=False), server_default='DRAFT', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skills_text', sa.Text(), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(skills_text, '')), 'B') || setweight(to_tsvector('english', coalesce(description, '') || ' ' || coalesce(responsibilities, '')), 'C') || setweight(to_tsvector('english', coalesce(department, '') || ' ' || coalesce(location, '')), 'D')", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_version', sa.String(length=20), nullable=True),
    sa.Column('embedding_source_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY')", name=op.f('ck_jobs_job_employment_type')),
    sa.CheckConstraint("experience_level IN ('ENTRY', 'JUNIOR', 'MID', 'SENIOR', 'LEAD')", name=op.f('ck_jobs_experience_level')),
    sa.CheckConstraint("min_education_level IN ('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE')", name=op.f('ck_jobs_job_min_education_level')),
    sa.CheckConstraint("status = 'DRAFT' OR published_at IS NOT NULL OR status = 'ARCHIVED'", name=op.f('ck_jobs_published_at_set')),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'PAUSED', 'CLOSED', 'ARCHIVED')", name=op.f('ck_jobs_job_status')),
    sa.CheckConstraint("workplace_type IN ('ONSITE', 'HYBRID', 'REMOTE')", name=op.f('ck_jobs_job_workplace_type')),
    sa.CheckConstraint('max_experience_years IS NULL OR max_experience_years >= min_experience_years', name=op.f('ck_jobs_experience_range_ordered')),
    sa.CheckConstraint('min_experience_years >= 0 AND min_experience_years <= 70', name=op.f('ck_jobs_min_experience_range')),
    sa.CheckConstraint('salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min', name=op.f('ck_jobs_salary_range_ordered')),
    sa.CheckConstraint('salary_min IS NULL OR salary_min >= 0', name=op.f('ck_jobs_salary_min_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], name=op.f('fk_jobs_hiring_manager_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_company_status', 'jobs', ['company_id', 'status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('ix_jobs_embedding_hnsw', 'jobs', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_jobs_hiring_manager_id'), 'jobs', ['hiring_manager_id'], unique=False)
    op.create_index('ix_jobs_location_trgm', 'jobs', ['location'], unique=False, postgresql_using='gin', postgresql_ops={'location': 'gin_trgm_ops'})
    op.create_index('ix_jobs_published', 'jobs', [sa.literal_column('published_at DESC')], unique=False, postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_index('ix_jobs_search_tsv', 'jobs', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_title_trgm', 'jobs', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('uq_jobs_active_duplicate', 'jobs', ['company_id', sa.literal_column('lower(title)'), sa.literal_column("lower(coalesce(location, ''))"), 'workplace_type'], unique=True, postgresql_where=sa.text("status IN ('DRAFT', 'PUBLISHED', 'PAUSED')"))
    op.create_table('recruiter_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_company_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recruiter_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_recruiter_profiles'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('bulk_import_batches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_files > 0', name=op.f('ck_bulk_import_batches_total_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_bulk_import_batches_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_bulk_import_batches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['background_tasks.id'], name=op.f('fk_bulk_import_batches_task_id_background_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_import_batches'))
    )
    op.create_index(op.f('ix_bulk_import_batches_company_id'), 'bulk_import_batches', ['company_id'], unique=False)
    op.create_table('candidate_job_matches',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('raw_cosine', sa.Float(), nullable=False),
    sa.Column('required_skill_score', sa.Float(), nullable=True),
    sa.Column('preferred_skill_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('preference_score', sa.Float(), nullable=True),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matching_version', sa.String(length=20), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('job_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 1', name=op.f('ck_candidate_job_matches_overall_range')),
    sa.CheckConstraint('semantic_score >= 0 AND semantic_score <= 1', name=op.f('ck_candidate_job_matches_semantic_range')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_candidate_job_matches_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidate_job_matches_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_job_matches')),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_candidate_job_matches_job_candidate')
    )
    op.create_index('ix_candidate_job_matches_candidate_score', 'candidate_job_matches', ['candidate_id', sa.literal_column('overall_score DESC')], unique=False)
    op.create_index('ix_candidate_job_matches_job_score', 'candidate_job_matches', ['job_id', sa.literal_column('overall_score DESC')], unique=False)
    op.create_table('candidate_languages',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=False),
    sa.Column('proficiency', sa.Enum('BASIC', 'CONVERSATIONAL', 'FLUENT', 'NATIVE', name='language_proficiency', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("proficiency IN ('BASIC', 'CONVERSATIONAL', 'FLUENT', 'NATIVE')", name=op.f('ck_candidate_languages_language_proficiency')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_candidate_languages_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_languages'))
    )
    op.create_index(op.f('ix_candidate_languages_candidate_id'), 'candidate_languages', ['candidate_id'], unique=False)
    op.create_index('uq_candidate_languages_lang', 'candidate_languages', ['candidate_id', sa.literal_column('lower(language)')], unique=True)
    op.create_table('candidate_skills',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skill_proficiency', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('years_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('source', sa.Enum('USER', 'RESUME', name='candidate_skill_source', native_enum=False, create_constraint=False), server_default='USER', nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'SUGGESTED', 'REJECTED', name='candidate_skill_status', native_enum=False, create_constraint=False), server_default='CONFIRMED', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("proficiency IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')", name=op.f('ck_candidate_skills_skill_proficiency')),
    sa.CheckConstraint("source IN ('USER', 'RESUME')", name=op.f('ck_candidate_skills_candidate_skill_source')),
    sa.CheckConstraint("status IN ('CONFIRMED', 'SUGGESTED', 'REJECTED')", name=op.f('ck_candidate_skills_candidate_skill_status')),
    sa.CheckConstraint('years_experience IS NULL OR (years_experience >= 0 AND years_experience <= 70)', name=op.f('ck_candidate_skills_years_range')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_candidate_skills_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_candidate_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_skills')),
    sa.UniqueConstraint('candidate_id', 'skill_id', name='uq_candidate_skills_candidate_skill')
    )
    op.create_index('ix_candidate_skills_skill_candidate', 'candidate_skills', ['skill_id', 'candidate_id'], unique=False)
    op.create_table('certifications',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('USER', 'RESUME', name='certification_source', native_enum=False, create_constraint=False), server_default='USER', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('USER', 'RESUME')", name=op.f('ck_certifications_certification_source')),
    sa.CheckConstraint('issued_on IS NULL OR expires_on IS NULL OR expires_on >= issued_on', name=op.f('ck_certifications_dates_ordered')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_certifications_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_index(op.f('ix_certifications_candidate_id'), 'certifications', ['candidate_id'], unique=False)
    op.create_table('educations',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree_level', sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE', name='degree_level', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Enum('USER', 'RESUME', name='education_source', native_enum=False, create_constraint=False), server_default='USER', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("degree_level IN ('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE')", name=op.f('ck_educations_degree_level')),
    sa.CheckConstraint("source IN ('USER', 'RESUME')", name=op.f('ck_educations_education_source')),
    sa.CheckConstraint('end_year IS NULL OR (end_year BETWEEN 1950 AND 2100)', name=op.f('ck_educations_end_year_range')),
    sa.CheckConstraint('start_year IS NULL OR (start_year BETWEEN 1950 AND 2100)', name=op.f('ck_educations_start_year_range')),
    sa.CheckConstraint('start_year IS NULL OR end_year IS NULL OR end_year >= start_year', name=op.f('ck_educations_years_ordered')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_educations_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educations'))
    )
    op.create_index(op.f('ix_educations_candidate_id'), 'educations', ['candidate_id'], unique=False)
    op.create_table('experiences',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('USER', 'RESUME', name='experience_source', native_enum=False, create_constraint=False), server_default='USER', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('USER', 'RESUME')", name=op.f('ck_experiences_experience_source')),
    sa.CheckConstraint('NOT is_current OR end_date IS NULL', name=op.f('ck_experiences_current_has_no_end')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_experiences_dates_ordered')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_experiences_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    op.create_index(op.f('ix_experiences_candidate_id'), 'experiences', ['candidate_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('requirement', sa.Enum('REQUIRED', 'PREFERRED', name='job_skill_requirement', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('min_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("requirement IN ('REQUIRED', 'PREFERRED')", name=op.f('ck_job_skills_job_skill_requirement')),
    sa.CheckConstraint('min_years IS NULL OR min_years >= 0', name=op.f('ck_job_skills_min_years_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_job_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills')),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skills_job_skill')
    )
    op.create_index('ix_job_skills_skill_job', 'job_skills', ['skill_id', 'job_id'], unique=False)
    op.create_table('resumes',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='resume_status', native_enum=False, create_constraint=False), server_default='UPLOADED', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED')", name=op.f('ck_resumes_resume_status')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_resumes_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_resumes_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index('ix_resumes_candidate_created', 'resumes', ['candidate_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_resumes_one_primary', 'resumes', ['candidate_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('saved_jobs',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_saved_jobs_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_saved_jobs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'job_id', name=op.f('pk_saved_jobs'))
    )
    op.create_index('ix_saved_jobs_candidate_created', 'saved_jobs', ['candidate_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('applications',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN', name='application_status', native_enum=False, create_constraint=False), server_default='APPLIED', nullable=False),
    sa.Column('source', sa.String(length=30), server_default='DIRECT', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN')", name=op.f('ck_applications_application_status')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_applications_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_applied_at', 'applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.create_index('ix_applications_candidate_applied', 'applications', ['candidate_id', sa.literal_column('applied_at DESC')], unique=False)
    op.create_index('ix_applications_job_applied', 'applications', ['job_id', sa.literal_column('applied_at DESC')], unique=False)
    op.create_index('ix_applications_job_status', 'applications', ['job_id', 'status'], unique=False)
    op.create_index('ix_applications_resume', 'applications', ['resume_id'], unique=False, postgresql_where=sa.text('resume_id IS NOT NULL'))
    op.create_index('uq_applications_live_per_candidate_job', 'applications', ['job_id', 'candidate_id'], unique=True, postgresql_where=sa.text("status <> 'WITHDRAWN'"))
    op.create_table('bulk_import_items',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREATED', 'DUPLICATE', 'FAILED', name='import_item_status', native_enum=False, create_constraint=False), server_default='PENDING', nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'CREATED', 'DUPLICATE', 'FAILED')", name=op.f('ck_bulk_import_items_import_item_status')),
    sa.ForeignKeyConstraint(['batch_id'], ['bulk_import_batches.id'], name=op.f('fk_bulk_import_items_batch_id_bulk_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_bulk_import_items_candidate_id_candidate_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_bulk_import_items_resume_id_resumes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_import_items'))
    )
    op.create_index('ix_bulk_import_items_batch_status', 'bulk_import_items', ['batch_id', 'status'], unique=False)
    op.create_table('resume_documents',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_resume_documents_size_positive')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_documents_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_resume_documents_storage_key'))
    )
    op.create_index(op.f('ix_resume_documents_resume_id'), 'resume_documents', ['resume_id'], unique=False)
    op.create_index('ix_resume_documents_sha256', 'resume_documents', ['sha256'], unique=False)
    op.create_table('application_notes',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_notes_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_application_notes_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_notes'))
    )
    op.create_index('ix_application_notes_app_created', 'application_notes', ['application_id', 'created_at'], unique=False)
    op.create_table('application_status_history',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN', name='history_from_status', native_enum=False, create_constraint=False), nullable=True),
    sa.Column('to_status', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN', name='history_to_status', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("from_status IN ('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN')", name=op.f('ck_application_status_history_history_from_status')),
    sa.CheckConstraint("to_status IN ('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN')", name=op.f('ck_application_status_history_history_to_status')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_application_status_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_status_history_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_status_history'))
    )
    op.create_index('ix_application_history_app_created', 'application_status_history', ['application_id', 'created_at'], unique=False)
    op.create_table('interviews',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('interview_type', sa.Enum('PHONE_SCREEN', 'TECHNICAL', 'BEHAVIORAL', 'PANEL', 'ONSITE', 'FINAL', name='interview_type', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='interview_status', native_enum=False, create_constraint=False), server_default='SCHEDULED', nullable=False),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('during', postgresql.TSTZRANGE(), sa.Computed("tstzrange(start_at, end_at, '[)')", persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('candidate_id'), '='), (sa.column('during'), '&&'), where=sa.text("status IN ('SCHEDULED', 'CONFIRMED', 'RESCHEDULED')"), using='gist', name='ex_interviews_candidate_no_overlap'),
    sa.CheckConstraint("end_at - start_at <= interval '12 hours'", name=op.f('ck_interviews_max_duration')),
    sa.CheckConstraint("interview_type IN ('PHONE_SCREEN', 'TECHNICAL', 'BEHAVIORAL', 'PANEL', 'ONSITE', 'FINAL')", name=op.f('ck_interviews_interview_type')),
    sa.CheckConstraint("status IN ('SCHEDULED', 'CONFIRMED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')", name=op.f('ck_interviews_interview_status')),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_interviews_end_after_start')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interviews_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name=op.f('fk_interviews_candidate_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_interviews_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_interviews_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index('ix_interviews_candidate_start', 'interviews', ['candidate_id', 'start_at'], unique=False)
    op.create_index('ix_interviews_company_start', 'interviews', ['company_id', 'start_at'], unique=False)
    op.create_index('ix_interviews_start', 'interviews', ['start_at'], unique=False)
    op.create_table('resume_processing_results',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='processing_status', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('text_char_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('was_truncated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_version', sa.String(length=20), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PROCESSING', 'COMPLETED', 'FAILED')", name=op.f('ck_resume_processing_results_processing_status')),
    sa.ForeignKeyConstraint(['document_id'], ['resume_documents.id'], name=op.f('fk_resume_processing_results_document_id_resume_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_processing_results_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_processing_results')),
    sa.UniqueConstraint('resume_id', name=op.f('uq_resume_processing_results_resume_id'))
    )
    op.create_table('interview_feedback',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('recommendation', sa.Enum('STRONG_HIRE', 'HIRE', 'NO_HIRE', 'STRONG_NO_HIRE', name='hire_recommendation', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("recommendation IN ('STRONG_HIRE', 'HIRE', 'NO_HIRE', 'STRONG_NO_HIRE')", name=op.f('ck_interview_feedback_hire_recommendation')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_interview_feedback_rating_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_interview_feedback_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_feedback_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_feedback')),
    sa.UniqueConstraint('interview_id', 'author_id', name='uq_interview_feedback_interview_author')
    )
    op.create_table('interview_participants',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('INTERVIEWER', 'OBSERVER', name='participant_role', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('during', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('user_id'), '='), (sa.column('during'), '&&'), where=sa.text("is_active AND role = 'INTERVIEWER'"), using='gist', name='ex_interview_participants_user_no_overlap'),
    sa.CheckConstraint("role IN ('INTERVIEWER', 'OBSERVER')", name=op.f('ck_interview_participants_participant_role')),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_participants_interview_id_interviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_participants')),
    sa.UniqueConstraint('interview_id', 'user_id', name='uq_interview_participants_interview_user')
    )
    op.create_index('ix_interview_participants_user', 'interview_participants', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('APPLICATION_SUBMITTED', 'APPLICATION_STATUS_CHANGED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_RESCHEDULED', 'INTERVIEW_CANCELLED', 'RESUME_PROCESSED', 'RESUME_FAILED', 'NEW_CANDIDATE_MATCH', 'NEW_JOB_RECOMMENDATION', 'BULK_IMPORT_COMPLETED', name='notification_type', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('interview_id', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("type IN ('APPLICATION_SUBMITTED', 'APPLICATION_STATUS_CHANGED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_RESCHEDULED', 'INTERVIEW_CANCELLED', 'RESUME_PROCESSED', 'RESUME_FAILED', 'NEW_CANDIDATE_MATCH', 'NEW_JOB_RECOMMENDATION', 'BULK_IMPORT_COMPLETED')", name=op.f('ck_notifications_notification_type')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_notifications_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_notifications_interview_id_interviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_notifications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_notifications_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notifications_user_dedupe')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('NOT is_read'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('NOT is_read'))
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_interview_participants_user', table_name='interview_participants')
    op.drop_table('interview_participants')
    op.drop_table('interview_feedback')
    op.drop_table('resume_processing_results')
    op.drop_index('ix_interviews_start', table_name='interviews')
    op.drop_index('ix_interviews_company_start', table_name='interviews')
    op.drop_index('ix_interviews_candidate_start', table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index('ix_application_history_app_created', table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index('ix_application_notes_app_created', table_name='application_notes')
    op.drop_table('application_notes')
    op.drop_index('ix_resume_documents_sha256', table_name='resume_documents')
    op.drop_index(op.f('ix_resume_documents_resume_id'), table_name='resume_documents')
    op.drop_table('resume_documents')
    op.drop_index('ix_bulk_import_items_batch_status', table_name='bulk_import_items')
    op.drop_table('bulk_import_items')
    op.drop_index('uq_applications_live_per_candidate_job', table_name='applications', postgresql_where=sa.text("status <> 'WITHDRAWN'"))
    op.drop_index('ix_applications_resume', table_name='applications', postgresql_where=sa.text('resume_id IS NOT NULL'))
    op.drop_index('ix_applications_job_status', table_name='applications')
    op.drop_index('ix_applications_job_applied', table_name='applications')
    op.drop_index('ix_applications_candidate_applied', table_name='applications')
    op.drop_index('ix_applications_applied_at', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_saved_jobs_candidate_created', table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index('uq_resumes_one_primary', table_name='resumes', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_resumes_candidate_created', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('ix_job_skills_skill_job', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_experiences_candidate_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_educations_candidate_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_certifications_candidate_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('ix_candidate_skills_skill_candidate', table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index('uq_candidate_languages_lang', table_name='candidate_languages')
    op.drop_index(op.f('ix_candidate_languages_candidate_id'), table_name='candidate_languages')
    op.drop_table('candidate_languages')
    op.drop_index('ix_candidate_job_matches_job_score', table_name='candidate_job_matches')
    op.drop_index('ix_candidate_job_matches_candidate_score', table_name='candidate_job_matches')
    op.drop_table('candidate_job_matches')
    op.drop_index(op.f('ix_bulk_import_batches_company_id'), table_name='bulk_import_batches')
    op.drop_table('bulk_import_batches')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('recruiter_profiles')
    op.drop_index('uq_jobs_active_duplicate', table_name='jobs', postgresql_where=sa.text("status IN ('DRAFT', 'PUBLISHED', 'PAUSED')"))
    op.drop_index('ix_jobs_title_trgm', table_name='jobs', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_jobs_search_tsv', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_published', table_name='jobs', postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.drop_index('ix_jobs_location_trgm', table_name='jobs', postgresql_using='gin', postgresql_ops={'location': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_jobs_hiring_manager_id'), table_name='jobs')
    op.drop_index('ix_jobs_embedding_hnsw', table_name='jobs', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_jobs_company_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('uq_candidate_profiles_company_email', table_name='candidate_profiles', postgresql_where=sa.text("source = 'IMPORTED' AND contact_email IS NOT NULL"))
    op.drop_index(op.f('ix_candidate_profiles_sourced_by_company_id'), table_name='candidate_profiles')
    op.drop_index('ix_candidate_profiles_searchable', table_name='candidate_profiles', postgresql_where=sa.text("is_searchable AND source = 'SELF'"))
    op.drop_index('ix_candidate_profiles_search_tsv', table_name='candidate_profiles', postgresql_using='gin')
    op.drop_index('ix_candidate_profiles_location_trgm', table_name='candidate_profiles', postgresql_using='gin', postgresql_ops={'location': 'gin_trgm_ops'})
    op.drop_index('ix_candidate_profiles_embedding_hnsw', table_name='candidate_profiles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_candidate_profiles_display_name_trgm', table_name='candidate_profiles', postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.drop_table('candidate_profiles')
    op.drop_index('uq_background_tasks_active_dedupe', table_name='background_tasks', postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('PENDING', 'RUNNING')"))
    op.drop_index('ix_background_tasks_status_created', table_name='background_tasks')
    op.drop_index('ix_background_tasks_creator', table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_created', table_name='audit_events')
    op.drop_index('ix_audit_events_company_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skill_aliases_skill_id'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index('ix_skills_name_trgm', table_name='skills', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_skills_family', table_name='skills')
    op.drop_table('skills')
    op.drop_index('uq_companies_name_lower', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
