"""Pure scoring: no database, no I/O — fully unit-testable.

Final score (a *ranking/relevance* score in [0, 1], **not** a probability of being hired):

    overall = Σ wᵢ·sᵢ / Σ wᵢ   over the components that apply to this job/candidate pair

    component            weight   notes
    -------------------  ------   ------------------------------------------------------------------------
    semantic similarity    0.30   calibrated cosine between job and candidate embeddings
    required skills        0.30   exact/alias = 1.0, same-family (e.g. MySQL↔PostgreSQL) = 0.5, else 0
    preferred skills       0.10   same rule
    experience             0.15   years vs. required range
    education              0.05   highest degree vs. minimum required
    preferences            0.10   workplace, location, employment type (salary is *not* scored)

Components that cannot be evaluated (the job lists no preferred skills, the candidate gave no preferences, …) are
dropped and the remaining weights renormalised, so missing data neither rewards nor punishes. A *qualification floor*
caps the overall score at 0.45 when the candidate covers < 25 % of the required skills: semantic proximity alone must
not put an under-qualified candidate on top.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from app.db.models import EducationLevel
from app.matching.representation import CandidateFeatures, JobFeatures, SkillRef, total_years_of_experience

WEIGHTS: dict[str, float] = {
    "semantic": 0.30,
    "required": 0.30,
    "preferred": 0.10,
    "experience": 0.15,
    "education": 0.05,
    "preference": 0.10,
}
RELATED_CREDIT = 0.5
FLOOR_COVERAGE = 0.25
FLOOR_CAP = 0.45

# Calibration of raw cosine similarity into [0, 1]. Averaged-word embeddings of two on-topic documents rarely fall below
# ~0.35 and strong matches sit near 0.8+, while unrelated documents hover around 0.1-0.25; the anchors were chosen
# from the labelled evaluation set (see docs/matching-evaluation.md, which is generated by `python -m app.matching.eval`).
COSINE_LOW = 0.25
COSINE_HIGH = 0.80
MATCHING_VERSION = "v1"


def calibrate_cosine(cosine: float) -> float:
    return max(0.0, min(1.0, (cosine - COSINE_LOW) / (COSINE_HIGH - COSINE_LOW)))


def semantic_band(score: float) -> str:
    return "HIGH" if score >= 0.7 else "MEDIUM" if score >= 0.4 else "LOW"


def overall_band(score: float) -> str:
    return "STRONG" if score >= 0.75 else "GOOD" if score >= 0.55 else "PARTIAL" if score >= 0.35 else "WEAK"


@dataclass(slots=True)
class SkillCoverage:
    score: float | None
    matched: list[dict[str, Any]]
    related: list[dict[str, Any]]
    missing: list[str]


def skill_coverage(wanted: list[SkillRef], have: list[SkillRef]) -> SkillCoverage:
    if not wanted:
        return SkillCoverage(None, [], [], [])
    by_id = {s.skill_id: s for s in have}
    by_family: dict[str, SkillRef] = {}
    for s in have:
        if s.family and s.family not in by_family:
            by_family[s.family] = s
    credit, matched, related, missing = 0.0, [], [], []
    for w in wanted:
        if w.skill_id in by_id:
            credit += 1.0
            matched.append({"name": w.name, "source": by_id[w.skill_id].source})
        elif w.family and w.family in by_family:
            credit += RELATED_CREDIT
            related.append({"required": w.name, "candidate_has": by_family[w.family].name})
        else:
            missing.append(w.name)
    return SkillCoverage(round(credit / len(wanted), 4), matched, related, missing)


@dataclass(slots=True)
class ExperienceResult:
    score: float | None
    status: str  # MEETS | BELOW | ABOVE | UNKNOWN | NOT_REQUIRED
    candidate_years: float | None
    text: str


def candidate_years(c: CandidateFeatures) -> float | None:
    if c.declared_years is not None:
        return float(c.declared_years)
    if c.experiences:
        return total_years_of_experience(c.experiences)
    return None


def _fmt(y: float) -> str:
    return f"{y:g}"


def experience_alignment(job: JobFeatures, years: float | None) -> ExperienceResult:
    lo, hi = float(job.min_experience_years or 0), job.max_experience_years
    if lo <= 0 and hi is None:
        return ExperienceResult(None, "NOT_REQUIRED", years, "No minimum experience required")
    need = f"{_fmt(lo)}+ years" if hi is None else f"{_fmt(lo)}–{_fmt(float(hi))} years"
    if years is None:
        return ExperienceResult(0.4, "UNKNOWN", None, f"Experience not provided (job asks for {need})")
    if years < lo:
        score = max(0.0, 1.0 - (lo - years) / max(lo, 1.0))
        return ExperienceResult(round(score, 4), "BELOW", years, f"{_fmt(years)} years vs {need} required")
    if hi is not None and years > float(hi):
        score = max(0.7, 1.0 - 0.05 * (years - float(hi)))
        return ExperienceResult(
            round(score, 4), "ABOVE", years, f"{_fmt(years)} years (above the {need} range)"
        )
    return ExperienceResult(1.0, "MEETS", years, f"{_fmt(years)} years vs {need} required")


def _level_rank(value: str | None) -> int | None:
    try:
        return EducationLevel(value).rank if value else None
    except ValueError:
        return None


@dataclass(slots=True)
class EducationResult:
    score: float | None
    status: str  # MEETS | BELOW | UNKNOWN | NOT_REQUIRED
    candidate_level: str | None
    required_level: str | None


def education_alignment(job: JobFeatures, levels: list[str]) -> EducationResult:
    required = _level_rank(job.min_education_level)
    if required is None:
        return EducationResult(None, "NOT_REQUIRED", None, None)
    ranks = [r for r in (_level_rank(lv) for lv in levels) if r is not None]
    if not ranks:
        return EducationResult(0.4, "UNKNOWN", None, job.min_education_level)
    best = max(ranks)
    best_level = list(EducationLevel)[best].value
    if best >= required:
        return EducationResult(1.0, "MEETS", best_level, job.min_education_level)
    return EducationResult(0.5 if best == required - 1 else 0.0, "BELOW", best_level, job.min_education_level)


_WORKPLACE_FIT: dict[str, dict[str, float]] = {
    "REMOTE": {"REMOTE": 1.0, "FLEXIBLE": 1.0, "HYBRID": 0.6, "ONSITE": 0.2},
    "HYBRID": {"HYBRID": 1.0, "FLEXIBLE": 1.0, "REMOTE": 0.6, "ONSITE": 0.6},
    "ONSITE": {"ONSITE": 1.0, "FLEXIBLE": 1.0, "HYBRID": 0.7, "REMOTE": 0.2},
}


def _location_fit(job_loc: str | None, cand_loc: str | None) -> tuple[float | None, str | None]:
    if not job_loc or not cand_loc:
        return None, None
    jp = [p.strip().casefold() for p in job_loc.split(",") if p.strip()]
    cp = [p.strip().casefold() for p in cand_loc.split(",") if p.strip()]
    if not jp or not cp:
        return None, None
    if jp[0] == cp[0]:
        return 1.0, "Same city"
    if jp[-1] == cp[-1]:
        return 0.6, "Same region/country"
    return 0.2, "Different location"


@dataclass(slots=True)
class PreferenceResult:
    score: float | None
    notes: dict[str, str]


def preference_alignment(job: JobFeatures, c: CandidateFeatures) -> PreferenceResult:
    parts: list[float] = []
    notes: dict[str, str] = {}
    if c.remote_preference:
        fit = _WORKPLACE_FIT.get(job.workplace_type, {}).get(c.remote_preference)
        if fit is not None:
            parts.append(fit)
            notes["workplace"] = (
                f"Job is {job.workplace_type.lower()}; candidate prefers {c.remote_preference.lower()}"
            )
    if job.workplace_type != "REMOTE":
        fit, note = _location_fit(job.location, c.location)
        if fit is not None and note:
            parts.append(fit)
            notes["location"] = note
    if c.employment_preference:
        eq = c.employment_preference == job.employment_type
        parts.append(1.0 if eq else 0.3)
        notes["employment"] = (
            "Employment type matches"
            if eq
            else f"Candidate prefers {c.employment_preference.replace('_', ' ').lower()}"
        )
    return PreferenceResult(round(sum(parts) / len(parts), 4) if parts else None, notes)


@dataclass(slots=True)
class MatchResult:
    overall: float
    semantic: float
    raw_cosine: float
    required: float | None
    preferred: float | None
    experience: float | None
    education: float | None
    preference: float | None
    explanation: dict[str, Any]


def combine(components: dict[str, float | None]) -> float:
    present = {k: v for k, v in components.items() if v is not None}
    total_w = sum(WEIGHTS[k] for k in present)
    if total_w == 0:
        return 0.0
    return sum(WEIGHTS[k] * v for k, v in present.items()) / total_w


def score_pair(job: JobFeatures, cand: CandidateFeatures, raw_cosine: float | None) -> MatchResult:
    """Score one (job, candidate) pair. ``raw_cosine`` is None when either side has no embedding yet."""
    cosine = float(raw_cosine) if raw_cosine is not None else 0.0
    semantic = calibrate_cosine(cosine) if raw_cosine is not None else 0.0
    req = skill_coverage(job.required, cand.skills)
    pref = skill_coverage(job.preferred, cand.skills)
    years = candidate_years(cand)
    exp = experience_alignment(job, years)
    edu = education_alignment(job, cand.education_levels)
    prefs = preference_alignment(job, cand)

    overall = combine(
        {
            "semantic": semantic,
            "required": req.score,
            "preferred": pref.score,
            "experience": exp.score,
            "education": edu.score,
            "preference": prefs.score,
        }
    )
    floor_applied = req.score is not None and req.score < FLOOR_COVERAGE
    if floor_applied:
        overall = min(overall, FLOOR_CAP)
    overall = round(max(0.0, min(1.0, overall)), 4)

    explanation: dict[str, Any] = {
        "band": overall_band(overall),
        "overall_percent": round(overall * 100),
        "skills": {
            "required": {
                "coverage": req.score,
                "matched": req.matched,
                "related": req.related,
                "missing": req.missing,
                "total": len(job.required),
            },
            "preferred": {
                "coverage": pref.score,
                "matched": pref.matched,
                "related": pref.related,
                "missing": pref.missing,
                "total": len(job.preferred),
            },
        },
        "experience": {
            "status": exp.status,
            "candidate_years": exp.candidate_years,
            "required_min": float(job.min_experience_years or 0),
            "required_max": float(job.max_experience_years) if job.max_experience_years is not None else None,
            "text": exp.text,
        },
        "education": {
            "status": edu.status,
            "candidate_level": edu.candidate_level,
            "required_level": edu.required_level,
        },
        "semantic": {
            "band": semantic_band(semantic) if raw_cosine is not None else "UNKNOWN",
            "score": round(semantic, 4),
            "cosine": round(cosine, 4) if raw_cosine is not None else None,
        },
        "preferences": prefs.notes,
        "qualification_floor_applied": floor_applied,
        "weights": dict(WEIGHTS.items()),
    }
    explanation["summary"] = build_summary(job, explanation)
    return MatchResult(
        overall=overall,
        semantic=round(semantic, 4),
        raw_cosine=round(cosine, 4),
        required=req.score,
        preferred=pref.score,
        experience=exp.score,
        education=edu.score,
        preference=prefs.score,
        explanation=explanation,
    )


def build_summary(job: JobFeatures, e: dict[str, Any]) -> str:
    """One recruiter-readable sentence. Derived only from the structured explanation (no extra inference)."""
    req = e["skills"]["required"]
    parts: list[str] = [f"{e['band'].title()} match"]
    if req["total"]:
        got = len(req["matched"])
        parts.append(
            f"covers {got} of {req['total']} required skills"
            + (f" (+{len(req['related'])} related)" if req["related"] else "")
        )
    if e["experience"]["status"] in ("MEETS", "ABOVE"):
        parts.append(f"experience: {e['experience']['text']}")
    elif e["experience"]["status"] == "BELOW":
        parts.append(f"below the experience requirement ({e['experience']['text']})")
    parts.append(f"semantic relevance {e['semantic']['band'].lower()}")
    if req["missing"]:
        parts.append("missing: " + ", ".join(req["missing"][:4]))
    return "; ".join(parts) + "."
